/* World of Trade — Learn · glossario
   Ogni voce: il termine, cosa significa, perché conta su un desk, e la lezione
   dove viene insegnato. Il campo `lesson` è verificato contro il curriculum dai test:
   un rimando a una lezione inesistente fa fallire la suite. */
window.GLOSSARY = [
  /* ── u1 · What a physical trade is ─────────────────────────────── */
  { term:'Physical trader', lesson:'u1l1',
    def:'Someone who buys a commodity from a producer, owns it while it moves, and sells it to a consumer.',
    why:'The money is made on the spread between the two contracts and on solving the logistics, not on predicting the price.' },
  { term:'Cargo', lesson:'u1l1',
    def:'A specific parcel of goods sold under one contract, usually one shipload or a defined tonnage.',
    why:'Everything — pricing, freight, finance, insurance, claims — is organised per cargo. It is the unit the whole business counts in.' },
  { term:'Gross margin', lesson:'u1l2',
    def:'Sale price minus purchase price, before any of the costs of moving and financing the goods.',
    why:'It is the number that looks good in a pitch and means nothing on its own.' },
  { term:'Net margin', lesson:'u1l2',
    def:'What is left after freight, financing, insurance, inspection, losses and demurrage.',
    why:'On physical cargoes the gap between gross and net is often most of the gross. This is the only margin that pays salaries.' },
  { term:'Working capital', lesson:'u1l2',
    def:'The cash tied up in a cargo between paying the seller and being paid by the buyer.',
    why:'A trader can be profitable on every deal and still run out of money. Volume needs funding, not just margin.' },
  { term:'Counterparty', lesson:'u1l4',
    def:'The other side of a contract — the producer you buy from or the consumer you sell to.',
    why:'A contract is only worth the counterparty behind it. Half of physical trading is deciding who you are willing to face.' },

  /* ── u2 · Incoterms ────────────────────────────────────────────── */
  { term:'Incoterms', lesson:'u2l1',
    def:'A standard set of three-letter trade terms defining who arranges and pays for each step, and where risk passes.',
    why:'Shorthand for a whole chunk of contract — but only for delivery, cost and risk. They say nothing about title, payment, applicable law or breach. FOB, CFR and CIF are sea-only rules: containerised cargo belongs on FCA, and using FOB for a box is a habit rather than a rule.' },
  { term:'FOB — Free On Board', lesson:'u2l1',
    def:'The seller delivers the goods on board the vessel at the load port; from that point cost and risk are the buyer’s.',
    why:'The benchmark term. The buyer charters the ship, so the buyer carries the freight market and the demurrage risk.' },
  { term:'CFR — Cost and Freight', lesson:'u2l2',
    def:'The seller pays the freight to the destination port, but risk still passes on loading.',
    why:'A seller quoting CFR is trading freight too, whether they mean to or not. Fix the ship or you are exposed.' },
  { term:'CIF — Cost, Insurance and Freight', lesson:'u2l2',
    def:'Like CFR, with the seller also buying marine insurance for the buyer’s benefit.',
    why:'The seller pays for insurance on goods that are already at the buyer’s risk, which confuses people constantly. Worse, under Incoterms 2020 the CIF minimum is Institute Cargo Clauses (C) — named perils — at 110% of invoice value. A buyer expecting all-risks has to write ICC (A) into the contract.' },
  { term:'EXW — Ex Works', lesson:'u2l3',
    def:'The buyer collects the goods at the seller’s premises and does everything from there.',
    why:'Maximum obligation on the buyer. Cheap on paper, and a nightmare if you cannot handle export clearance.' },
  { term:'DDP — Delivered Duty Paid', lesson:'u2l3',
    def:'The seller delivers to the named place with duties paid — the maximum obligation on the seller.',
    why:'The seller takes on customs and tax exposure in a country they may not operate in.' },
  { term:'Risk transfer', lesson:'u2l4',
    def:'The moment at which loss or damage stops being the seller’s problem and becomes the buyer’s.',
    why:'It is set by the incoterm, and it is not the same moment as payment or as ownership. Three different lines, three different dates.' },
  { term:'Title', lesson:'u2l4',
    def:'Legal ownership of the goods.',
    why:'Set by the contract and the bill of lading, not by the incoterm. You can bear the risk on goods you do not yet own.' },

  /* ── u3 · Pricing ──────────────────────────────────────────────── */
  { term:'Benchmark', lesson:'u3l1',
    def:'A published reference price — an exchange settlement or an assessed quote — that a physical contract prices against.',
    why:'Almost no physical cargo is priced as a flat number. It is priced as a benchmark plus or minus something.' },
  { term:'Premium / differential', lesson:'u3l1',
    def:'The amount added to or subtracted from the benchmark for a specific grade, origin or delivery point.',
    why:'This is where the trader’s judgement lives. The benchmark is public; the differential is the negotiation.' },
  { term:'Quotational period (QP)', lesson:'u3l2',
    def:'The period whose benchmark quotes set the price of the cargo — commonly the average over a window, but equally a single day, a declared date, or a month-plus offset.',
    why:'You are exposed to the market for the whole window, not on one day. Mismatched QPs between purchase and sale create risk out of nothing.' },
  { term:'Flat price', lesson:'u3l3',
    def:'The absolute price of the commodity, as opposed to a differential.',
    why:'It is the risk a futures hedge removes — and the least interesting risk on a physical desk.' },
  { term:'Basis', lesson:'u3l3',
    def:'Cash minus futures — the local physical price relative to the contract used to hedge it. It is quoted and traded as a price in its own right.',
    why:'A hedge converts flat price risk into basis risk. It does not remove risk, it changes which risk you hold.' },
  { term:'Contango', lesson:'u3l4',
    def:'Forward prices above spot: the market pays you to hold the goods and deliver later.',
    why:'It makes storage a trade, and it makes rolling a long hedge forward expensive every single month.' },
  { term:'Backwardation', lesson:'u3l4',
    def:'Forward prices below spot: the market wants the goods now.',
    why:'It punishes holding inventory and usually signals real physical tightness.' },
  { term:'Cost of carry', lesson:'u3l4',
    def:'Storage, insurance and financing for holding a commodity over time.',
    why:'The forward spread only pays if it is wider than the carry — and the carry moves with the flat price, because you finance the full value of the cargo. The same spread in dollars is a trade at $50 and a slow loss at $100.' },

  /* ── u4 · Hedging ──────────────────────────────────────────────── */
  { term:'Hedge', lesson:'u4l1',
    def:'An offsetting paper position taken so that a price move does not change the margin on the physical cargo.',
    why:'A hedge protects the margin you agreed. It is not a bet and it is not supposed to make money.' },
  { term:'Hedge ratio', lesson:'u4l2',
    def:'The size of the paper position relative to the physical exposure. Not automatically one-to-one: it depends on how much of the cargo is genuinely unpriced, and on how closely the hedge instrument tracks it.',
    why:'The first question is not how much to hedge but how much is actually exposed. A purchase and a sale on the same benchmark over the same quotational period already offset — hedging that is not prudence, it is a new position.' },
  { term:'Initial margin', lesson:'u4l3',
    def:'The deposit an exchange requires to open a futures position.',
    why:'It is cash locked up for the life of the hedge, and it scales with the size of your book.' },
  { term:'Variation margin', lesson:'u4l3',
    def:'The daily cash settlement of gains and losses on a futures position.',
    why:'This is the trap. The paper loss is cash today; the physical gain arrives at settlement. Well-hedged companies have died in that gap.' },
  { term:'Margin call', lesson:'u4l3',
    def:'The demand to post more cash because the position has moved against you.',
    why:'It does not care that you are hedged. It cares whether you have the money by tomorrow.' },
  { term:'Liquidity risk', lesson:'u4l3',
    def:'The risk of being unable to fund your obligations even though the position is sound.',
    why:'Different from price risk, and it is the one that actually closes desks.' },
  { term:'Basis risk', lesson:'u4l4',
    def:'The risk that the hedge and the cargo do not move together — different grade, place or timing.',
    why:'What a futures contract does not describe about your cargo is exactly what you keep.' },
  { term:'Cross hedge', lesson:'u4l4',
    def:'Hedging with a related but not identical contract, because no future exists for what you actually hold.',
    why:'Better than nothing and worse than it looks. The correlation you relied on is the first thing to break in a crisis.' },

  /* ── u5 · Trade finance ────────────────────────────────────────── */
  { term:'Working capital gap', lesson:'u5l1',
    def:'The number of days between paying the supplier and being paid by the buyer.',
    why:'Every day in that gap is financed. It is the single biggest constraint on how much a desk can trade.' },
  { term:'Letter of credit (LC)', lesson:'u5l2',
    def:'An irrevocable undertaking by a bank to pay the seller against a specified set of documents, independent of the sale contract.',
    why:'It replaces buyer risk with bank risk — but only with the bank you actually accept. Unconfirmed, you still carry the issuing bank and its country; confirmed, a bank of your own choosing steps in front. It is why cargoes move between strangers at all.' },
  { term:'Documentary compliance', lesson:'u5l2',
    def:'Presenting documents that are consistent with the credit and with each other. Under UCP 600 the data need not be identical, but it must not conflict.',
    why:'The bank pays against documents, not against cargo. A perfect cargo with an inconsistent document set does not get paid.' },
  { term:'Discrepancy', lesson:'u5l2',
    def:'Any mismatch between the presented documents and the terms of the credit.',
    why:'A misspelled port or a claused bill of lading is enough. The bank is entitled to refuse, and often does.' },
  { term:'Borrowing base', lesson:'u5l1',
    def:'A credit facility sized against the value of inventory and receivables that secure it.',
    why:'It is how physical desks finance volume. When prices fall, the base shrinks exactly when cash is needed most.' },
  { term:'Counterparty credit exposure', lesson:'u5l3',
    def:'How much you would lose if a specific counterparty failed to perform right now.',
    why:'Default costs both the receivable and the replacement trade. It is measured, with limits, not estimated by feel.' },
  { term:'Prepayment', lesson:'u5l1',
    def:'Paying a producer before the goods are shipped.',
    why:'It buys access to supply and converts a trading position into unsecured lending. Priced accordingly, or it should be.' },

  /* ── u6 · Execution and documents ──────────────────────────────── */
  { term:'Laycan', lesson:'u6l1',
    def:'Laydays and cancelling: the window in which the vessel must be presented ready to load.',
    why:'Arrive after the cancelling date and the counterparty can walk away from the charter.' },
  { term:'Cancelling date', lesson:'u6l1',
    def:'The date after which the charterer may cancel the charter if the vessel has not tendered a valid Notice of Readiness.',
    why:'It is an option for the charterer, never an obligation to accept. The exposure is the owner’s: a cancelled vessel has to be replaced at the spot rate, in a market that knows she is open. It protects against a late ship — it is no help at all when it is your cargo that is late.' },
  { term:'Nomination', lesson:'u6l1',
    def:'Formally naming the vessel to the counterparty for acceptance.',
    why:'Under FOB the buyer nominates. Most execution disputes are about whether a step like this happened on time and in writing.' },
  { term:'Notice of Readiness (NOR)', lesson:'u6l2',
    def:'The master’s declaration that the vessel has arrived and is ready to work cargo.',
    why:'A valid NOR triggers laytime, which then starts after the contractual turn time — often six hours. Validity turns on whether the vessel had really arrived and was really ready. If the notice was bad the clock may never have started, unless the charterer worked cargo anyway and waived the point.' },
  { term:'Laytime', lesson:'u6l2',
    def:'The free time allowed for loading or discharging under the charterparty.',
    why:'It is the allowance you are given. Everything past it has a price per day.' },
  { term:'Demurrage', lesson:'u6l2',
    def:'Agreed damages paid per day for time used beyond laytime.',
    why:'Pre-agreed, so nobody has to prove a loss — which is why it gets claimed hard. It scales with hours, not tonnes.' },
  { term:'Despatch', lesson:'u6l2',
    def:'A payment back to the charterer for finishing loading or discharge early.',
    why:'Only exists if the charterparty provides for it: normal in dry bulk, rare on tankers.' },
  { term:'Deadfreight', lesson:'u6l2',
    def:'Freight payable on cargo you contracted to load but did not.',
    why:'The ship reserved space it can no longer sell, so you pay for the empty tonnes.' },
  { term:'Bill of lading (B/L)', lesson:'u6l3',
    def:'Receipt for the goods, evidence of the contract of carriage, and — when negotiable — a document of title.',
    why:'It is what lets a floating cargo be sold by endorsing a piece of paper. It is also what you cannot afford to lose.' },
  { term:'Clean bill of lading', lesson:'u6l3',
    def:'A bill of lading with no adverse remark about the apparent condition of the goods on loading.',
    why:'A claused, or "dirty", B/L is a discrepancy under a letter of credit and stops payment.' },
  { term:'Letter of indemnity (LOI)', lesson:'u6l3',
    def:'A promise to cover the consequences of discharging cargo without the original bills of lading.',
    why:'Routine in oil, and a real liability: you have given away the cargo and kept the risk.' },
  { term:'Independent inspector', lesson:'u6l4',
    def:'A third party appointed to determine loaded or discharged quantity and quality.',
    why:'Neither side would accept the other’s figure, so both accept a third party’s. The contract says whose certificate is final.' },
  { term:'Outturn', lesson:'u6l4',
    def:'The quantity actually measured at the discharge port.',
    why:'It is never exactly the bill of lading figure. The contract decides who absorbs the difference.' },
  { term:'Franchise', lesson:'u6l4',
    def:'A threshold below which nothing is payable — but once the loss passes it, the whole loss is payable, without deducting the threshold.',
    why:'That last part is what separates it from a deductible, which is always subtracted. On a 0.5% franchise a 0.4% loss pays nothing and a 0.6% loss pays the full 0.6%. Small losses get budgeted, and a claim just over the line is worth far more than one just under.' },
  { term:'Time bar', lesson:'u6l4',
    def:'The deadline for presenting a claim with its supporting documents.',
    why:'Samples degrade and crews change. Two clocks run at once and both are fatal: notice under the sale contract or charterparty, often 30 to 90 days with full documents, and cargo claims against the carrier, one year from delivery under Hague-Visby. Meeting the first and missing the second still leaves you with nothing.' },

  /* ── u7 · Freight and chartering ───────────────────────────────── */
  { term:'Voyage charter', lesson:'u8l1',
    def:'Hiring a ship for one defined voyage at a freight rate, with the owner paying the voyage costs.',
    why:'You buy a known freight rate and the owner runs the ship. What stays with you is the clock: laytime and demurrage are yours.' },
  { term:'Time charter', lesson:'u8l1',
    def:'Hiring a ship with crew by the day, with the charterer paying bunkers and port costs.',
    why:'You buy flexibility and take the operational risk with it. Delay is not a dispute here, it is an invoice.' },
  { term:'Hire', lesson:'u8l1',
    def:'The daily payment under a time charter.',
    why:'It runs whether the ship is working or waiting, which is why there is no demurrage on a time charter. The exception is off-hire: when the vessel cannot perform for reasons on the owner’s side — breakdown, drydock, deviation — hire stops. It is the most negotiated clause in the charter.' },
  { term:'Charterparty', lesson:'u8l1',
    def:'The contract between shipowner and charterer.',
    why:'Laytime, demurrage exceptions, NOR validity and time bars all live in here. Most freight arguments are readings of this document.' },
  { term:'Lumpsum freight', lesson:'u8l2',
    def:'A single fixed freight amount regardless of the quantity actually loaded.',
    why:'Load less and your cost per tonne rises. It puts the quantity risk on you.' },
  { term:'Worldscale', lesson:'u8l2',
    def:'A published annual flat rate in dollars per tonne for each tanker route; quotes are a percentage of it.',
    why:'WS175 means 75% above the flat rate. A flat rate revision in January can move your freight cost with no market move at all.' },
  { term:'Time charter equivalent (TCE)', lesson:'u8l3',
    def:'Voyage revenue minus voyage costs, divided by the days the voyage takes.',
    why:'It is how an owner compares your cargo with every other offer. Learn to compute it and refusals stop being surprising.' },
  { term:'Bunkers', lesson:'u8l3',
    def:'The vessel’s fuel oil, bought and burned by whoever is paying for the voyage.',
    why:'Usually the largest and most volatile voyage cost. It is why an owner will not hold a freight quote open for long.' },
  { term:'Ballast leg', lesson:'u8l4',
    def:'The part of the voyage the ship sails empty to reach the load port.',
    why:'You pay for it inside your freight rate. A cargo that suits where the ship already is will always be quoted cheaper.' },
  { term:'Vessel position', lesson:'u8l4',
    def:'Where a ship is and when it becomes open for its next cargo.',
    why:'Knowing which ships are open where is a genuine physical edge that no screen price gives you.' },
  { term:'Forward freight agreement (FFA)', lesson:'u8l4',
    def:'A paper contract settling against a published freight route index.',
    why:'It hedges the freight market but not your specific ship or route. Same logic as any hedge: you keep the basis.' },

  /* ── u8 · Desk risk ────────────────────────────────────────────── */
  { term:'Net position', lesson:'u7l1',
    def:'The physical book and the paper book added together.',
    why:'Only the net moves with the outright price. It is the first number a risk manager asks for.' },
  { term:'Mark to market', lesson:'u7l1',
    def:'Revaluing a position at today’s market price rather than at what you paid.',
    why:'It is how a loss becomes visible before it is realised — and how a margin call gets calculated.' },
  { term:'Concentration', lesson:'u7l2',
    def:'Exposure clustered in one counterparty, grade, origin, port or lender.',
    why:'The same total exposure is far more dangerous in one place. Concentration hides in geography and financing, not only in names.' },
  { term:'Position limit', lesson:'u7l2',
    def:'The maximum exposure a desk is allowed to carry, set independently of the desk.',
    why:'A limit the risk-taker can raise is not a limit. Independence is the whole control.' },
  { term:'Value at Risk (VaR)', lesson:'u7l3',
    def:'A loss threshold: a 95% one-day VaR of $2m means about one day in twenty you would expect to lose more than that.',
    why:'It is a threshold, not a ceiling, and it says nothing about how bad the bad day is. Treating it as a worst case is the standard misreading.' },
  { term:'Stress test', lesson:'u7l3',
    def:'Costing a specific severe scenario without assigning it a probability.',
    why:'VaR describes the weather. A stress test asks what the storm costs.' },
  { term:'Stack and roll', lesson:'u7l4',
    def:'Hedging long-dated commitments with short-dated futures rolled forward repeatedly.',
    why:'The Metallgesellschaft case: the position was arguably defensible and the funding was not. Rolling in contango costs money every month.' },
  /* ── termini usati nei desk specialistici, prima assenti ────────── */
  { term:'Sanctions screening', lesson:'a12l1',
    def:'Checking counterparties, vessels, banks, cargo origin and ultimate ownership against sanctions lists before committing to a trade.',
    why:'It is the first gate, not a formality after the price is agreed. A breach can end the company rather than the trade, it cannot be priced away, and on a physical desk it is a routine daily task — not an exotic one.' },
  { term:'Know your counterparty (KYC)', lesson:'a12l1',
    def:'Establishing who you are actually dealing with: legal entity, ownership, control, and who stands behind the obligation.',
    why:'Many trading counterparties are thin entities. Both the credit question and the compliance question have the same answer — who is really on the other side.' },
  { term:'Beneficial ownership', lesson:'a12l1',
    def:'The natural person who ultimately owns or controls a counterparty, behind whatever chain of companies sits in front.',
    why:'Sanctions and credit both follow control, not the name on the contract. A clean-looking entity can be owned by someone you may not trade with.' },
  { term:'Arbitrage', lesson:'a1l4',
    def:'Buying in one market and selling in another where the delivered economics are better — across location, time or quality.',
    why:'With optionality, this is where a physical trader’s margin actually comes from. It closes when enough people see it, which is why the work is finding it before the netback is obvious.' },
  { term:'Optionality', lesson:'a2l2',
    def:'Any right in a contract to choose later — destination, timing, quantity tolerance, grade.',
    why:'Every flexibility belongs to someone. If the contract does not say the choice is yours, assume it is being exercised against you, and price it.' },
  { term:'Netback', lesson:'a1l3',
    def:'The destination value less freight, handling and every other cost of getting there, expressed back at the loading point.',
    why:'It is what makes two destinations comparable. Two markets can show the same benchmark and pay you very differently once the route is paid for.' },
  { term:'Off-hire', lesson:'u8l1',
    def:'A period under a time charter when hire stops because the vessel cannot perform for reasons on the owner’s side.',
    why:'The charterer’s only real protection in a time charter, and the most negotiated clause in it. Without off-hire, hire runs through a breakdown you did not cause.' },
  { term:'Deductible', lesson:'u6l4',
    def:'An amount always subtracted from a claim, whatever the size of the loss.',
    why:'The opposite of a franchise, which pays the whole loss once the threshold is passed. Confusing the two changes what you can recover, and the contract will only say one of them.' },
  { term:'Force majeure', lesson:'a12l4',
    def:'A contract clause excusing performance when a defined event outside either party’s control makes it impossible.',
    why:'It decides who bears the cost when nobody is at fault — which is when the amounts are largest. The listed events, the notice deadlines and the consequences differ enormously between contracts, so it is never boilerplate.' },
  { term:'Treatment and refining charges (TC/RC)', lesson:'a7l5',
    def:'What a smelter deducts for turning concentrate into metal: a charge per dry tonne of concentrate and a charge per unit of metal.',
    why:'The smelter’s margin and the miner’s cost, in one number. They move with concentrate availability, and they decide whether a concentrate trade works at all.' },
  { term:'LME warrant', lesson:'a7l1',
    def:'A document giving title to a specific lot of metal in an LME-approved warehouse.',
    why:'It is how metal ownership changes hands without the metal moving, which is what makes exchange delivery work — and what makes a defective warrant a title problem rather than a paperwork problem.' },
  { term:'Crack spread', lesson:'a8l2',
    def:'The margin between crude and the refined products made from it.',
    why:'The refining margin, and a spread you can hedge directly. It is the signal that moves crude demand and product supply at the same time.' },
  { term:'General average', lesson:'u6l4',
    def:'A maritime principle where all cargo interests share the cost of a deliberate sacrifice or extraordinary expense made to save the voyage.',
    why:'A declaration freezes your cargo until security is posted, whether or not your parcel was touched. It is an operational event that takes cash and time, not just a legal curiosity.' },
];
