/* World of Trade — Learn · glossario
   Ogni voce: il termine, cosa significa, perché conta su un desk, e la lezione
   dove viene insegnato. Il campo `lesson` è verificato contro il curriculum dai test:
   un rimando a una lezione inesistente fa fallire la suite. */
window.GLOSSARY = [
  /* ── u1 · What a physical trade is ─────────────────────────────── */
  { term:'Physical trader', lesson:'u1l1',
    def:'Someone who buys a commodity from a producer, owns it while it moves, and sells it to a consumer.',
    why:'The money is made on the spread between the two contracts and on solving the logistics, not on predicting the price.' },
  { term:'Cargo', lesson:'u1l1',
    def:'A specific parcel of goods sold under one contract, usually one shipload or a defined tonnage.',
    why:'Everything — pricing, freight, finance, insurance, claims — is organised per cargo. It is the unit the whole business counts in.' },
  { term:'Gross margin', lesson:'u1l2',
    def:'Sale price minus purchase price, before any of the costs of moving and financing the goods.',
    why:'It is the number that looks good in a pitch and means nothing on its own.' },
  { term:'Net margin', lesson:'u1l2',
    def:'What is left after freight, financing, insurance, inspection, losses and demurrage.',
    why:'On physical cargoes the gap between gross and net is often most of the gross. This is the only margin that pays salaries.' },
  { term:'Working capital', lesson:'u1l2',
    def:'The cash tied up in a cargo between paying the seller and being paid by the buyer.',
    why:'A trader can be profitable on every deal and still run out of money. Volume needs funding, not just margin.' },
  { term:'Counterparty', lesson:'u1l4',
    def:'The other side of a contract — the producer you buy from or the consumer you sell to.',
    why:'A contract is only worth the counterparty behind it. Half of physical trading is deciding who you are willing to face.' },

  /* ── u2 · Incoterms ────────────────────────────────────────────── */
  { term:'Incoterms', lesson:'u2l1',
    def:'A standard set of three-letter trade terms defining who arranges and pays for each step, and where risk passes.',
    why:'Shorthand for a whole chunk of contract — but only for delivery, cost and risk. They say nothing about title, payment, applicable law or breach. FOB, CFR and CIF are sea-only rules: containerised cargo belongs on FCA, and using FOB for a box is a habit rather than a rule.' },
  { term:'FOB — Free On Board', lesson:'u2l1',
    def:'The seller delivers the goods on board the vessel at the load port; from that point cost and risk are the buyer’s.',
    why:'The benchmark term. The buyer charters the ship, so the buyer carries the freight market and the demurrage risk.' },
  { term:'CFR — Cost and Freight', lesson:'u2l2',
    def:'The seller pays the freight to the destination port, but risk still passes on loading.',
    why:'A seller quoting CFR is trading freight too, whether they mean to or not. Fix the ship or you are exposed.' },
  { term:'CIF — Cost, Insurance and Freight', lesson:'u2l2',
    def:'Like CFR, with the seller also buying marine insurance for the buyer’s benefit.',
    why:'The seller pays for insurance on goods that are already at the buyer’s risk, which confuses people constantly. Worse, under Incoterms 2020 the CIF minimum is Institute Cargo Clauses (C) — named perils — at 110% of invoice value. A buyer expecting all-risks has to write ICC (A) into the contract.' },
  { term:'EXW — Ex Works', lesson:'u2l3',
    def:'The buyer collects the goods at the seller’s premises and does everything from there.',
    why:'Maximum obligation on the buyer. Cheap on paper, and a nightmare if you cannot handle export clearance.' },
  { term:'DDP — Delivered Duty Paid', lesson:'u2l3',
    def:'The seller delivers to the named place with duties paid — the maximum obligation on the seller.',
    why:'The seller takes on customs and tax exposure in a country they may not operate in.' },
  { term:'Risk transfer', lesson:'u2l4',
    def:'The moment at which loss or damage stops being the seller’s problem and becomes the buyer’s.',
    why:'It is set by the incoterm, and it is not the same moment as payment or as ownership. Three different lines, three different dates.' },
  { term:'Title', lesson:'u2l4',
    def:'Legal ownership of the goods.',
    why:'Set by the contract and the bill of lading, not by the incoterm. You can bear the risk on goods you do not yet own.' },

  /* ── u3 · Pricing ──────────────────────────────────────────────── */
  { term:'Benchmark', lesson:'u3l1',
    def:'A published reference price — an exchange settlement or an assessed quote — that a physical contract prices against.',
    why:'Almost no physical cargo is priced as a flat number. It is priced as a benchmark plus or minus something.' },
  { term:'Premium / differential', lesson:'u3l1',
    def:'The amount added to or subtracted from the benchmark for a specific grade, origin or delivery point.',
    why:'This is where the trader’s judgement lives. The benchmark is public; the differential is the negotiation.' },
  { term:'Quotational period (QP)', lesson:'u3l2',
    def:'The period whose benchmark quotes set the price of the cargo — commonly the average over a window, but equally a single day, a declared date, or a month-plus offset.',
    why:'You are exposed to the market for the whole window, not on one day. Mismatched QPs between purchase and sale create risk out of nothing.' },
  { term:'Flat price', lesson:'u3l3',
    def:'The absolute price of the commodity, as opposed to a differential.',
    why:'It is the risk a futures hedge removes — and the least interesting risk on a physical desk.' },
  { term:'Basis', lesson:'u3l3',
    def:'Cash minus futures — the local physical price relative to the contract used to hedge it. It is quoted and traded as a price in its own right.',
    why:'A hedge converts flat price risk into basis risk. It does not remove risk, it changes which risk you hold.' },
  { term:'Contango', lesson:'u3l4',
    def:'Forward prices above spot: the market pays you to hold the goods and deliver later.',
    why:'It makes storage a trade, and it makes rolling a long hedge forward expensive every single month.' },
  { term:'Backwardation', lesson:'u3l4',
    def:'Forward prices below spot: the market wants the goods now.',
    why:'It punishes holding inventory and usually signals real physical tightness.' },
  { term:'Cost of carry', lesson:'u3l4',
    def:'Storage, insurance and financing for holding a commodity over time.',
    why:'The forward spread only pays if it is wider than the carry — and the carry moves with the flat price, because you finance the full value of the cargo. The same spread in dollars is a trade at $50 and a slow loss at $100.' },

  /* ── u4 · Hedging ──────────────────────────────────────────────── */
  { term:'Hedge', lesson:'u4l1',
    def:'An offsetting paper position taken so that a price move does not change the margin on the physical cargo.',
    why:'A hedge protects the margin you agreed. It is not a bet and it is not supposed to make money.' },
  { term:'Hedge ratio', lesson:'u4l2',
    def:'The size of the paper position relative to the physical exposure. Not automatically one-to-one: it depends on how much of the cargo is genuinely unpriced, and on how closely the hedge instrument tracks it.',
    why:'The first question is not how much to hedge but how much is actually exposed. A purchase and a sale on the same benchmark over the same quotational period already offset — hedging that is not prudence, it is a new position.' },
  { term:'Initial margin', lesson:'u4l3',
    def:'The deposit an exchange requires to open a futures position.',
    why:'It is cash locked up for the life of the hedge, and it scales with the size of your book.' },
  { term:'Variation margin', lesson:'u4l3',
    def:'The daily cash settlement of gains and losses on a futures position.',
    why:'This is the trap. The paper loss is cash today; the physical gain arrives at settlement. Well-hedged companies have died in that gap.' },
  { term:'Margin call', lesson:'u4l3',
    def:'The demand to post more cash because the position has moved against you.',
    why:'It does not care that you are hedged. It cares whether you have the money by tomorrow.' },
  { term:'Liquidity risk', lesson:'u4l3',
    def:'The risk of being unable to fund your obligations even though the position is sound.',
    why:'Different from price risk, and it is the one that actually closes desks.' },
  { term:'Basis risk', lesson:'u4l4',
    def:'The risk that the hedge and the cargo do not move together — different grade, place or timing.',
    why:'What a futures contract does not describe about your cargo is exactly what you keep.' },
  { term:'Cross hedge', lesson:'u4l4',
    def:'Hedging with a related but not identical contract, because no future exists for what you actually hold.',
    why:'Better than nothing and worse than it looks. The correlation you relied on is the first thing to break in a crisis.' },

  /* ── u5 · Trade finance ────────────────────────────────────────── */
  { term:'Working capital gap', lesson:'u5l1',
    def:'The number of days between paying the supplier and being paid by the buyer.',
    why:'Every day in that gap is financed. It is the single biggest constraint on how much a desk can trade.' },
  { term:'Letter of credit (LC)', lesson:'u5l2',
    def:'An irrevocable undertaking by a bank to pay the seller against a specified set of documents, independent of the sale contract.',
    why:'It replaces buyer risk with bank risk — but only with the bank you actually accept. Unconfirmed, you still carry the issuing bank and its country; confirmed, a bank of your own choosing steps in front. It is why cargoes move between strangers at all.' },
  { term:'Documentary compliance', lesson:'u5l2',
    def:'Presenting documents that are consistent with the credit and with each other. Under UCP 600 the data need not be identical, but it must not conflict.',
    why:'The bank pays against documents, not against cargo. A perfect cargo with an inconsistent document set does not get paid.' },
  { term:'Discrepancy', lesson:'u5l2',
    def:'Any mismatch between the presented documents and the terms of the credit.',
    why:'A misspelled port or a claused bill of lading is enough. The bank is entitled to refuse, and often does.' },
  { term:'Borrowing base', lesson:'u5l1',
    def:'A revolving credit limit set by the value of eligible inventory and receivables, recalculated regularly with a haircut on each.',
    why:'The limit falls with the market, so borrowing capacity shrinks at the same moment hedges are calling for margin. Liquidity tightens from both sides at once.' },
  { term:'Counterparty credit exposure', lesson:'u5l3',
    def:'How much you would lose if a specific counterparty failed to perform right now.',
    why:'Default costs both the receivable and the replacement trade. It is measured, with limits, not estimated by feel.' },
  { term:'Prepayment', lesson:'u5l1',
    def:'Cash advanced to a producer and repaid through future deliveries of the commodity rather than in money.',
    why:'It converts a credit exposure into an operational one: if the producer stops producing you hold a claim instead of a cargo.' },

  /* ── u6 · Execution and documents ──────────────────────────────── */
  { term:'Laycan', lesson:'u6l1',
    def:'Laydays and cancelling: the window in which the vessel must be presented ready to load.',
    why:'Arrive after the cancelling date and the counterparty can walk away from the charter.' },
  { term:'Cancelling date', lesson:'u6l1',
    def:'The date after which the charterer may cancel the charter if the vessel has not tendered a valid Notice of Readiness.',
    why:'It is an option for the charterer, never an obligation to accept. The exposure is the owner’s: a cancelled vessel has to be replaced at the spot rate, in a market that knows she is open. It protects against a late ship — it is no help at all when it is your cargo that is late.' },
  { term:'Nomination', lesson:'u6l1',
    def:'Formally naming the vessel to the counterparty for acceptance.',
    why:'Under FOB the buyer nominates. Most execution disputes are about whether a step like this happened on time and in writing.' },
  { term:'Notice of Readiness (NOR)', lesson:'u6l2',
    def:'The master’s declaration that the vessel has arrived and is ready to work cargo.',
    why:'A valid NOR triggers laytime, which then starts after the contractual turn time — often six hours. Validity turns on whether the vessel had really arrived and was really ready. If the notice was bad the clock may never have started, unless the charterer worked cargo anyway and waived the point.' },
  { term:'Laytime', lesson:'u6l2',
    def:'The free time allowed for loading or discharging under the charterparty.',
    why:'It is the allowance you are given. Everything past it has a price per day.' },
  { term:'Demurrage', lesson:'u6l2',
    def:'Agreed damages paid per day for time used beyond laytime.',
    why:'Pre-agreed, so nobody has to prove a loss — which is why it gets claimed hard. It scales with hours, not tonnes.' },
  { term:'Despatch', lesson:'u6l2',
    def:'A payment back to the charterer for finishing loading or discharge early.',
    why:'Only exists if the charterparty provides for it: normal in dry bulk, rare on tankers.' },
  { term:'Deadfreight', lesson:'u6l2',
    def:'Freight payable on cargo you contracted to load but did not.',
    why:'The ship reserved space it can no longer sell, so you pay for the empty tonnes.' },
  { term:'Bill of lading (B/L)', lesson:'u6l3',
    def:'Receipt for the goods, evidence of the contract of carriage, and — when negotiable — a document of title.',
    why:'It is what lets a floating cargo be sold by endorsing a piece of paper. It is also what you cannot afford to lose.' },
  { term:'Clean bill of lading', lesson:'u6l3',
    def:'A bill of lading with no adverse remark about the apparent condition of the goods on loading.',
    why:'A claused, or "dirty", B/L is a discrepancy under a letter of credit and stops payment.' },
  { term:'Letter of indemnity (LOI)', lesson:'u6l3',
    def:'A promise to cover the consequences of discharging cargo without the original bills of lading.',
    why:'Routine in oil, and a real liability: you have given away the cargo and kept the risk.' },
  { term:'Independent inspector', lesson:'u6l4',
    def:'A third party appointed to determine loaded or discharged quantity and quality.',
    why:'Neither side would accept the other’s figure, so both accept a third party’s. The contract says whose certificate is final.' },
  { term:'Outturn', lesson:'u6l4',
    def:'The quantity actually measured at the discharge port.',
    why:'It is never exactly the bill of lading figure. The contract decides who absorbs the difference.' },
  { term:'Franchise', lesson:'u6l4',
    def:'A threshold below which nothing is payable — but once the loss passes it, the whole loss is payable, without deducting the threshold.',
    why:'That last part is what separates it from a deductible, which is always subtracted. On a 0.5% franchise a 0.4% loss pays nothing and a 0.6% loss pays the full 0.6%. Small losses get budgeted, and a claim just over the line is worth far more than one just under.' },
  { term:'Time bar', lesson:'u6l4',
    def:'The deadline for presenting a claim with its supporting documents.',
    why:'Samples degrade and crews change. Two clocks run at once and both are fatal: notice under the sale contract or charterparty, often 30 to 90 days with full documents, and cargo claims against the carrier, one year from delivery under Hague-Visby. Meeting the first and missing the second still leaves you with nothing.' },

  /* ── u7 · Freight and chartering ───────────────────────────────── */
  { term:'Voyage charter', lesson:'u8l1',
    def:'Hiring a ship for one defined voyage at a freight rate, with the owner paying the voyage costs.',
    why:'You buy a known freight rate and the owner runs the ship. What stays with you is the clock: laytime and demurrage are yours.' },
  { term:'Time charter', lesson:'u8l1',
    def:'Hiring a ship with crew by the day, with the charterer paying bunkers and port costs.',
    why:'You buy flexibility and take the operational risk with it. Delay is not a dispute here, it is an invoice.' },
  { term:'Hire', lesson:'u8l1',
    def:'The daily payment under a time charter.',
    why:'It runs whether the ship is working or waiting, which is why there is no demurrage on a time charter. The exception is off-hire: when the vessel cannot perform for reasons on the owner’s side — breakdown, drydock, deviation — hire stops. It is the most negotiated clause in the charter.' },
  { term:'Charterparty', lesson:'u8l1',
    def:'The contract between shipowner and charterer.',
    why:'Laytime, demurrage exceptions, NOR validity and time bars all live in here. Most freight arguments are readings of this document.' },
  { term:'Lumpsum freight', lesson:'u8l2',
    def:'A single fixed freight amount regardless of the quantity actually loaded.',
    why:'Load less and your cost per tonne rises. It puts the quantity risk on you.' },
  { term:'Worldscale', lesson:'u8l2',
    def:'A published annual flat rate in dollars per tonne for each tanker route; quotes are a percentage of it.',
    why:'WS175 means 75% above the flat rate. A flat rate revision in January can move your freight cost with no market move at all.' },
  { term:'Time charter equivalent (TCE)', lesson:'u8l3',
    def:'Voyage revenue minus voyage costs, divided by the days the voyage takes.',
    why:'It is how an owner compares your cargo with every other offer. Learn to compute it and refusals stop being surprising.' },
  { term:'Bunkers', lesson:'u8l3',
    def:'The vessel’s fuel oil, bought and burned by whoever is paying for the voyage.',
    why:'Usually the largest and most volatile voyage cost. It is why an owner will not hold a freight quote open for long.' },
  { term:'Ballast leg', lesson:'u8l4',
    def:'The part of the voyage the ship sails empty to reach the load port.',
    why:'You pay for it inside your freight rate. A cargo that suits where the ship already is will always be quoted cheaper.' },
  { term:'Vessel position', lesson:'u8l4',
    def:'Where a ship is and when it becomes open for its next cargo.',
    why:'Knowing which ships are open where is a genuine physical edge that no screen price gives you.' },
  { term:'Forward freight agreement (FFA)', lesson:'u8l4',
    def:'A paper contract settling against a published freight route index.',
    why:'It hedges the freight market but not your specific ship or route. Same logic as any hedge: you keep the basis.' },

  /* ── u8 · Desk risk ────────────────────────────────────────────── */
  { term:'Net position', lesson:'u7l1',
    def:'The physical book and the paper book added together.',
    why:'Only the net moves with the outright price. It is the first number a risk manager asks for.' },
  { term:'Mark to market', lesson:'u7l1',
    def:'Revaluing a position at today’s market price rather than at what you paid.',
    why:'It is how a loss becomes visible before it is realised — and how a margin call gets calculated.' },
  { term:'Concentration', lesson:'u7l2',
    def:'Exposure clustered in one counterparty, grade, origin, port or lender.',
    why:'The same total exposure is far more dangerous in one place. Concentration hides in geography and financing, not only in names.' },
  { term:'Position limit', lesson:'u7l2',
    def:'The maximum exposure a desk is allowed to carry, set independently of the desk.',
    why:'A limit the risk-taker can raise is not a limit. Independence is the whole control.' },
  { term:'Value at Risk (VaR)', lesson:'u7l3',
    def:'A loss threshold: a 95% one-day VaR of $2m means about one day in twenty you would expect to lose more than that.',
    why:'It is a threshold, not a ceiling, and it says nothing about how bad the bad day is. Treating it as a worst case is the standard misreading.' },
  { term:'Stress test', lesson:'u7l3',
    def:'Costing a specific severe scenario without assigning it a probability.',
    why:'VaR describes the weather. A stress test asks what the storm costs.' },
  { term:'Stack and roll', lesson:'u7l4',
    def:'Hedging long-dated commitments with short-dated futures rolled forward repeatedly.',
    why:'The Metallgesellschaft case: the position was arguably defensible and the funding was not. Rolling in contango costs money every month.' },
  /* ── termini usati nei desk specialistici, prima assenti ────────── */
  { term:'Sanctions screening', lesson:'u9l1',
    def:'Checking counterparties, vessels, banks, cargo origin and ultimate ownership against sanctions lists before committing to a trade.',
    why:'It is the first gate, not a formality after the price is agreed. A breach can end the company rather than the trade, it cannot be priced away, and on a physical desk it is a routine daily task — not an exotic one.' },
  { term:'Know your counterparty (KYC)', lesson:'u9l2',
    def:'Establishing who you are actually dealing with: legal entity, ownership, control, and who stands behind the obligation.',
    why:'Many trading counterparties are thin entities. Both the credit question and the compliance question have the same answer — who is really on the other side.' },
  { term:'Beneficial ownership', lesson:'u9l2',
    def:'The natural person who ultimately owns or controls a counterparty, behind whatever chain of companies sits in front.',
    why:'Sanctions and credit both follow control, not the name on the contract. A clean-looking entity can be owned by someone you may not trade with.' },
  { term:'Arbitrage', lesson:'a1l4',
    def:'Buying in one market and selling in another where the delivered economics are better — across location, time or quality.',
    why:'With optionality, this is where a physical trader’s margin actually comes from. It closes when enough people see it, which is why the work is finding it before the netback is obvious.' },
  { term:'Optionality', lesson:'a2l2',
    def:'Any right in a contract to choose later — destination, timing, quantity tolerance, grade.',
    why:'Every flexibility belongs to someone. If the contract does not say the choice is yours, assume it is being exercised against you, and price it.' },
  { term:'Netback', lesson:'a1l3',
    def:'The destination value less freight, handling and every other cost of getting there, expressed back at the loading point.',
    why:'It is what makes two destinations comparable. Two markets can show the same benchmark and pay you very differently once the route is paid for.' },
  { term:'Off-hire', lesson:'u8l1',
    def:'A period under a time charter when hire stops because the vessel cannot perform for reasons on the owner’s side.',
    why:'The charterer’s only real protection in a time charter, and the most negotiated clause in it. Without off-hire, hire runs through a breakdown you did not cause.' },
  { term:'Deductible', lesson:'u6l4',
    def:'An amount always subtracted from a claim, whatever the size of the loss.',
    why:'The opposite of a franchise, which pays the whole loss once the threshold is passed. Confusing the two changes what you can recover, and the contract will only say one of them.' },
  { term:'Force majeure', lesson:'a12l4',
    def:'A contract clause excusing performance when a defined event outside either party’s control makes it impossible.',
    why:'It decides who bears the cost when nobody is at fault — which is when the amounts are largest. The listed events, the notice deadlines and the consequences differ enormously between contracts, so it is never boilerplate.' },
  { term:'Treatment and refining charges (TC/RC)', lesson:'a7l5',
    def:'What a smelter deducts for turning concentrate into metal: a charge per dry tonne of concentrate and a charge per unit of metal.',
    why:'The smelter’s margin and the miner’s cost, in one number. They move with concentrate availability, and they decide whether a concentrate trade works at all.' },
  { term:'LME warrant', lesson:'a7l1',
    def:'A document giving title to a specific lot of metal in an LME-approved warehouse.',
    why:'It is how metal ownership changes hands without the metal moving, which is what makes exchange delivery work — and what makes a defective warrant a title problem rather than a paperwork problem.' },
  { term:'Crack spread', lesson:'a8l2',
    def:'The margin between crude and the refined products made from it.',
    why:'The refining margin, and a spread you can hedge directly. It is the signal that moves crude demand and product supply at the same time.' },
  { term:'General average', lesson:'u6l4',
    def:'A maritime principle where all cargo interests share the cost of a deliberate sacrifice or extraordinary expense made to save the voyage.',
    why:'A declaration freezes your cargo until security is posted, whether or not your parcel was touched. It is an operational event that takes cash and time, not just a legal curiosity.' },
  { term:'Double financing', lesson:'u9l3',
    def:'The same cargo pledged as security to more than one lender at the same time.',
    why:'It is possible because lenders finance against documents, and documents can be duplicated. It is behind some of the largest collapses in the business, and the defence is verification independent of whoever hands you the paper.' },
  { term:'Warehouse receipt fraud', lesson:'u9l3',
    def:'Financing or buying against a receipt for stored goods that are not there, or are pledged to someone else.',
    why:'Everyone checks the paper and nobody checks the shed. The control is confirming the stock with a party that has no interest in the answer.' },
  { term:'Secondary sanctions', lesson:'u9l1',
    def:'Measures that target non-US parties for dealing with sanctioned persons, even outside US territory.',
    why:'Combined with the fact that dollar payments clear through the US system, this is how a trade between two European companies ends up inside US jurisdiction.' },
  { term:'Dual-use goods', lesson:'u9l1',
    def:'Goods with both civilian and military applications, subject to export licensing.',
    why:'Classification is the seller\u2019s problem before shipment, not the buyer\u2019s problem after. Getting it wrong is an export control offence, not a commercial dispute.' },
  { term:'Red flag', lesson:'u9l4',
    def:'A signal that a trade should be stopped and re-examined before it goes further.',
    why:'Price far off market, pressure to sign before checks finish, routing with no commercial logic, payment from an unrelated party. None is subtle; they fail as controls only when someone decides not to slow down.' },
  /* ── u10 · Carbon and compliance cost ──────────────────────────── */
  { term:'EU ETS allowance', lesson:'u10l1',
    def:'A permit to emit one tonne of CO₂ equivalent, surrendered against verified emissions.',
    why:'Since 2026 it covers shipping in full, so it is a freight cost line that has to be estimated before you quote, not after the invoice arrives.' },
  { term:'CBAM', lesson:'u10l2',
    def:'The EU mechanism that charges importers for the carbon embedded in producing goods such as steel, aluminium, cement and fertiliser.',
    why:'It prices the factory, not the voyage. The cost depends on emissions data your supplier has to produce, and the fallback default values are punitive.' },
  { term:'Embedded emissions', lesson:'u10l2',
    def:'The greenhouse gases released in making a product, expressed per tonne of the product.',
    why:'Multiply by tonnage and by the certificate price and you have a landed cost item that does not appear anywhere in the commodity price.' },
  { term:'De minimis threshold', lesson:'u10l2',
    def:'Under CBAM, an annual 50-tonne cumulative mass limit below which an importer is exempt.',
    why:'It exempts roughly nine importers in ten while still capturing about 99% of embedded emissions, because the tonnage sits with a few large buyers.' },
  { term:'FuelEU Maritime', lesson:'u10l3',
    def:'The EU rule limiting the greenhouse gas intensity of energy used on board, measured well-to-wake, against a 2020 baseline of 91.16 gCO₂e/MJ.',
    why:'It regulates intensity rather than volume, so a fuel that looks clean at the funnel can still fail once its production emissions are counted.' },
  { term:'Sulphur cap', lesson:'u10l3',
    def:'The IMO limit on sulphur in marine fuel: 0.50% m/m globally and 0.10% inside emission control areas.',
    why:'It created the spread between compliant and high-sulphur fuel, and that spread is the entire economic case for a scrubber.' },
  { term:'Mass balance', lesson:'u10l4',
    def:'A chain-of-custody rule allowing certified and uncertified material to mix physically, provided the certified quantity withdrawn never exceeds the quantity added.',
    why:'It is an accounting rule rather than a physical one, which is why the books are audited so hard and why a break destroys a premium you have already sold.' },
  { term:'EUDR', lesson:'u10l5',
    def:'The EU deforestation regulation, requiring goods to be deforestation-free, legally produced and covered by a due diligence statement with plot geolocation.',
    why:'It applies to large and medium operators from 30 December 2026. Volume without coordinates cannot be placed on the EU market at all — it is a market closure, not a fine.' },

  /* ── u11 · Insurance and casualty ──────────────────────────────── */
  { term:'Institute Cargo Clauses', lesson:'u11l2',
    def:'The standard sets of marine cargo cover: A covers all risks subject to exclusions, B and C cover only listed perils.',
    why:'A works by exclusion and C by inclusion. That reversal decides who has to prove what, which usually matters more than the premium difference.' },
  { term:'Inherent vice', lesson:'u11l2',
    def:'A quality in the goods themselves that causes their deterioration without any external accident.',
    why:'It is excluded from every set of clauses. No policy insures goods against being what they are, which makes load-port inspection and packing specifications risk management.' },
  { term:'General average bond', lesson:'u11l3',
    def:'The undertaking a cargo owner gives, usually with an underwriter’s guarantee, to secure its future contribution.',
    why:'Insured, it is routine paperwork. Uninsured, you post cash and your working capital sits with the adjuster for months or years.' },
  { term:'Subrogation', lesson:'u11l4',
    def:'The insurer’s right, once it has paid you, to step into your shoes and recover from whoever caused the loss.',
    why:'It is why underwriters care about your time bars even after paying. Prejudice the recovery and they can reduce the payment by what you destroyed.' },
  { term:'Under-insurance', lesson:'u11l5',
    def:'Insuring for less than the full value, which makes the assured a co-insurer for the missing proportion.',
    why:'Average applies to partial losses too, so you carry a share of every claim and not only of a total loss.' },
  { term:'Transit clause', lesson:'u11l6',
    def:'The clause defining when cover attaches and when it ends, typically warehouse to warehouse with a time limit at destination.',
    why:'Cargo parked in a terminal while you look for a buyer has often stepped outside the policy without anyone noticing.' },

  /* ── u12 · Contracts and disputes ──────────────────────────────── */
  { term:'GAFTA / FOSFA', lesson:'u12l1',
    def:'The standard contract forms of the grain and the oils and fats trades, with settled wording for quality, delivery, default and arbitration.',
    why:'Their value is shared meaning. A bespoke clause dropped into the middle can disapply a remedy or a time bar somewhere else in the form.' },
  { term:'Default clause', lesson:'u12l1',
    def:'The clause fixing what happens, and at what price, when one party fails to perform.',
    why:'It turns a broken trade into arithmetic against the market on the day of default, instead of an argument about your onward sales.' },
  { term:'New York Convention', lesson:'u12l2',
    def:'The treaty under which arbitral awards are recognised and enforced across most jurisdictions.',
    why:'It is the reason trade disputes go to arbitration: a foreign court judgment often cannot be enforced where your counterparty keeps its assets.' },
  { term:'Washout', lesson:'u12l4',
    def:'An agreement to cancel offsetting contracts between the same parties and settle the price difference in cash.',
    why:'It realises the margin while saving the freight, the finance and the operational risk of a voyage that served no commercial purpose.' },
  { term:'Circle', lesson:'u12l4',
    def:'A chain of sales that returns to an earlier seller, so the same cargo is contracted round in a loop.',
    why:'Settled by netting differences around the ring rather than delivering. The point is to close the loop cleanly, not to pretend it never formed.' },
  { term:'Trade credit insurance', lesson:'u12l5',
    def:'Cover indemnifying a seller against non-payment by the buyer, subject to a co-insured share and a limit per buyer.',
    why:'It is credit risk, not cargo risk. The limit can be withdrawn for future shipments, and that withdrawal is itself a warning worth acting on.' },
  { term:'Demand guarantee', lesson:'u12l5',
    def:'A bank undertaking to pay against a compliant demand, independently of any dispute under the underlying contract.',
    why:'Its autonomy is the point: the bank pays and the argument happens afterwards. That cuts both ways, so an abusive call is a real risk.' },
  /* ── u13 · Structure and tax ───────────────────────────────────── */
  { term:'Arm’s length principle', lesson:'u13l2',
    def:'The rule that companies in the same group must price transactions between them as independent parties would have done.',
    why:'Without it a group could move profit anywhere by choosing an internal number. It is the foundation on which every transfer pricing argument is built.' },
  { term:'Sixth method', lesson:'u13l2',
    def:'A transfer pricing rule used in several Latin American countries that prices commodity exports at the quotation on the shipment date, unless earlier evidence of a fixing exists.',
    why:'It turns the quotational period into a documentary obligation: register the fix when you make it, or the cargo is priced on the day it sailed.' },
  { term:'Permanent establishment', lesson:'u13l3',
    def:'A taxable presence created in a country by a fixed place of business, or by an agent who habitually concludes contracts there.',
    why:'Activity creates it, not intention. A travelling trader who negotiates and closes abroad can create one for their employer without anybody deciding to.' },
  { term:'Substance', lesson:'u13l3',
    def:'People, premises, decision-making and risk genuinely located where the profit is booked.',
    why:'It is what turns a structure from a description into a fact. An entity booking a large margin with no traders is the pattern authorities look for first.' },
  { term:'Pillar Two', lesson:'u13l4',
    def:'The OECD global minimum tax setting a 15% effective floor for groups with consolidated revenue of at least €750 million, with a top-up collected where the rate falls short.',
    why:'It does not stop a country offering a low rate — it collects the difference elsewhere, so the benefit of being taxed below 15% is no longer kept by the group.' },
  { term:'Domestic top-up tax', lesson:'u13l4',
    def:'A national charge bringing local entities up to the 15% floor, so the shortfall is collected at home rather than by another jurisdiction.',
    why:'Switzerland introduced one from 2024. It is the clearest sign that competition between jurisdictions has moved away from the headline rate.' },
  { term:'Recoverable VAT', lesson:'u13l5',
    def:'Indirect tax paid on a purchase that will be refunded, but only after a delay that varies by jurisdiction.',
    why:'Recoverable does not mean free. Every day between paying it and getting it back is financed like any other working capital, and a slow refund can decide whether a route is worth trading.' },

  /* ── u14 · Structured deals and assets ─────────────────────────── */
  { term:'Offtake agreement', lesson:'u14l2',
    def:'A commitment to buy a defined share of a producer’s output over time, usually at a formula price.',
    why:'It turns uncertain sales into bankable revenue for the producer, which is often what lets a project be financed at all — and it secures the trader a place in the flow.' },
  { term:'Tolling', lesson:'u14l2',
    def:'Paying a processor a fee to convert material you continue to own, rather than selling it and buying the product back.',
    why:'You keep the price risk on both input and output while the processor keeps operational risk. The guaranteed yield, not the fee, is where the money quietly sits.' },
  { term:'Collateral management agreement', lesson:'u14l3',
    def:'An arrangement under which an independent party controls pledged stock on the lender’s behalf.',
    why:'It exists because the industry has repeatedly found the same warehouse receipts pledged to several banks at once.' },
  { term:'Streaming agreement', lesson:'u14l4',
    def:'An upfront payment giving the right to buy a share of a mine’s future production at a fixed low price.',
    why:'There is no repayment obligation to enforce: if the ore is not there, nothing is delivered and nothing can be claimed. Geology and the operator matter more than any credit rating.' },
  { term:'Royalty', lesson:'u14l4',
    def:'A right to a percentage of a producer’s revenue or profit, with no obligation to pay anything further.',
    why:'Unlike a stream it never touches the metal, so it carries no operating exposure — a different instrument that is often confused with one.' },
  { term:'Throughput agreement', lesson:'u14l5',
    def:'A contract for the right to move a volume through a terminal over a period, usually with a minimum commitment.',
    why:'It buys access without buying the asset, but the minimum turns a variable cost into a fixed one. It pays only if you have the flow to fill it.' },
];
