  /* @CONTENT-OVERHAUL-V6_1
     Lesson-specific additions. These factories exist to make every specialist
     lesson teach its own desk skill instead of being filled from a desk-wide bag. */
  EXTRA.a1.push(
    R => { const start=r(R,36,64,4), draw=r(R,4,16,2), days=30; const end=start-draw; const rate=round(draw/days,2); return numeric(`Stocks fall from ${start} Mt to ${end} Mt over ${days} days. Average inventory draw per day?`,rate,'Mt/day',`${draw} ÷ ${days} = ${rate} Mt/day.`,.01); },
    R => { const near=r(R,680,840,10), spread=r(R,-35,35,5), deferred=near-spread; return numeric(`Nearby futures are $${near}/t and deferred futures are $${deferred}/t. What is nearby minus deferred? Use a negative number for contango.`,spread,'$/t',`${near} − ${deferred} = $${spread}/t.`); },
    R => { const a=r(R,700,900,10), fa=r(R,20,55,5), b=a+r(R,-30,40,10), fb=r(R,20,55,5); const nA=a-fa, nB=b-fb, diff=nA-nB; return numeric(`Destination A pays $${a}/t with $${fa}/t freight. Destination B pays $${b}/t with $${fb}/t freight. By how much does A's netback exceed B's?`,diff,'$/t',`(${a} − ${fa}) − (${b} − ${fb}) = $${diff}/t.`); },
    R => { const feed=r(R,620,780,10), yieldPct=r(R,82,94,2), product=r(R,760,940,10), cost=r(R,20,50,5); const rev=product*yieldPct/100; const margin=round(rev-feed-cost,1); return numeric(`One tonne of feed costs $${feed}. Saleable yield is ${yieldPct}% and product value is $${product}/t. Processing cost is $${cost}/t feed. Simple margin per tonne of feed?`,margin,'$/t',`${product} × ${yieldPct}% − ${feed} − ${cost} = $${margin}/t feed.`,.1); },
    R => { const demand=r(R,90,130), supply=demand+r(R,-5,5), outage=r(R,2,6), demandRev=r(R,-3,3); const newBal=(supply-outage)-(demand+demandRev); return numeric(`Initial demand is ${demand} Mt and supply ${supply} Mt. A ${outage} Mt supply outage occurs and demand is revised by ${demandRev>=0?'+':''}${demandRev} Mt. New balance (supply − demand)?`,newBal,'Mt',`(${supply} − ${outage}) − (${demand} ${demandRev>=0?'+':'−'} ${Math.abs(demandRev)}) = ${newBal} Mt.`); },
    R => choice('Why compare inventories with their normal seasonal range rather than only with last month?',['Commodity stocks often have predictable seasonal builds and draws','Seasonality removes price risk','A monthly change is always meaningless','Only annual data matter'],0,'A normal seasonal draw can look bullish in isolation. Context tells you whether inventory behaviour is actually unusual.'),
    R => { const spread=r(R,12,36,4), storage=r(R,3,10), finance=r(R,2,8); const net=spread-storage-finance; return numeric(`Deferred value is $${spread}/t above prompt. Storage costs $${storage}/t and finance $${finance}/t. Net carry before losses?`,net,'$/t',`${spread} − ${storage} − ${finance} = $${net}/t.`); },
    R => choice('When does a regional arbitrage normally close?',['When delivered netbacks converge enough that the route no longer covers its costs and risks','When benchmarks have the same name','When freight reaches zero','Only when inventories are empty'],0,'Arbitrage is an all-in delivered comparison. Once the netback advantage disappears, the trade stops paying.'),
    R => choice('Why can a small change in processing yield matter more than a small move in the headline benchmark?',['Yield changes the amount of saleable output from every tonne of feed','Yield is only an accounting convention','Benchmarks never matter','Processing costs are fixed by law'],0,'A few yield points applied to large throughput can move the processing margin materially.'),
    R => choice('A market view should include an invalidation condition because…',['You need to know which new fact would prove the thesis wrong','It guarantees the forecast','It removes model risk','It replaces position limits'],0,'A thesis without a falsifiable trigger becomes a story that can survive any evidence.')
  );

  EXTRA.a2.push(
    R => { const qty=r(R,20,60,10)*1000, opt=10, repl=r(R,6,20,2); const extra=qty*opt/100; const loss=extra*repl; return numeric(`A buyer has a +${opt}% quantity option on ${qty.toLocaleString('en-US')} t at a fixed sale price. If replacement supply is $${repl}/t more expensive when they exercise the extra volume, downside on the optional tonnes?`,loss,'$',`${qty.toLocaleString('en-US')} × ${opt}% × $${repl} = ${money(loss)}.`); },
    R => { const qty=r(R,20,70,10)*1000, move=r(R,4,18,2); return numeric(`Purchase prices in Month 1 and sale prices in Month 2 on ${qty.toLocaleString('en-US')} t. The Month-2 minus Month-1 spread moves $${move}/t against you. Approximate timing P&L?`,-qty*move,'$',`${qty.toLocaleString('en-US')} × $${move} = ${money(qty*move)} loss.`); },
    R => { const a=r(R,18,42,2), b=a+r(R,-8,8,2), qty=r(R,20,60,10)*1000; const diff=(a-b)*qty; return numeric(`Origin A gives a delivered margin of $${a}/t and Origin B $${b}/t on ${qty.toLocaleString('en-US')} t. Contribution advantage of A over B?`,diff,'$',`(${a} − ${b}) × ${qty.toLocaleString('en-US')} = ${money(diff)}.`); },
    R => { const margin=r(R,10,28,2), qty=r(R,20,60,10)*1000, capital=r(R,8,24,2)*1000000, days=r(R,30,120,15); const ret=round((margin*qty/capital)*(365/days)*100,1); return numeric(`A deal earns $${margin}/t on ${qty.toLocaleString('en-US')} t, ties up ${money(capital)} for ${days} days. Approximate annualised return on capital?`,ret,'%',`(${margin} × ${qty.toLocaleString('en-US')} ÷ ${money(capital)}) × (365 ÷ ${days}) × 100 ≈ ${ret}%.`,.1); },
    R => { const gross=r(R,18,45,3), prob=r(R,5,20,5), loss=r(R,20,60,5); const expected=round(gross-(prob/100)*loss,1); return numeric(`Gross expected margin is $${gross}/t. A ${prob}% chance of an execution problem would cost $${loss}/t. Simple expected margin after that risk?`,expected,'$/t',`${gross} − ${prob}% × ${loss} = $${expected}/t.`,.1); },
    R => choice('Why should a trader price a quantity tolerance explicitly?',['Because the party choosing the volume owns an option on the marginal tonnes','Because tolerances never get exercised','Because quantity is only an operations issue','Because exchanges require it'],0,'A tolerance changes how much you may have to source or place at future market conditions.'),
    R => { const m1=r(R,700,900,10), m2=m1+r(R,-30,30,5), qty=r(R,20,60,10)*1000; const pnl=(m2-m1)*qty; return numeric(`You are economically long the Month-2 versus Month-1 spread on ${qty.toLocaleString('en-US')} t. Month 1 settles $${m1}/t and Month 2 $${m2}/t. Spread P&L?`,pnl,'$',`(${m2} − ${m1}) × ${qty.toLocaleString('en-US')} = ${money(pnl)}.`); },
    R => choice('A location arbitrage is real only when…',['The delivered margin survives freight, quality, finance, taxes and execution constraints','The FOB quote is the cheapest','Two benchmark screens differ','The vessel is already at sea'],0,'Physical arbitrage is a chain of executable costs and rights, not a screen-price comparison.'),
    R => { const gross=r(R,25,55,5), finance=r(R,3,10), credit=r(R,1,8), ops=r(R,2,9); const net=gross-finance-credit-ops; return numeric(`Headline margin $${gross}/t, finance $${finance}/t, expected credit cost $${credit}/t and execution reserve $${ops}/t. Risk-adjusted margin?`,net,'$/t',`${gross} − ${finance} − ${credit} − ${ops} = $${net}/t.`); }
  );

  EXTRA.a3.push(
    R => { const freight=r(R,700,1400,100)*1000, bunkers=r(R,180,520,20)*1000, port=r(R,80,240,20)*1000, days=r(R,25,55,5); const tce=round((freight-bunkers-port)/days); return numeric(`Gross freight revenue ${money(freight)}, bunkers ${money(bunkers)}, port/other voyage costs ${money(port)}, total voyage ${days} days. Approximate TCE?`,tce,'$/day',`(${money(freight)} − ${money(bunkers)} − ${money(port)}) ÷ ${days} = ${money(tce)}/day.`); },
    R => { const wait=r(R,1,5), hire=r(R,16,36,2)*1000; return numeric(`A time-chartered vessel waits ${wait} days before the agreed loading window. Hire is ${money(hire)}/day. Direct waiting-hire cost?`,wait*hire,'$',`${wait} × ${money(hire)} = ${money(wait*hire)}.`); },
    R => { const window=r(R,5,12), eta=r(R,1,4); const slack=window-eta; return numeric(`A laycan window spans ${window} days. Your vessel ETA uncertainty is ±${eta} days. Ignoring other delays, how many days of nominal window remain beyond the two-sided ETA uncertainty?`,slack,'days',`${window} − 2 × ${eta} = ${slack} days.`); },
    R => choice('What must be checked before treating a Notice of Readiness as valid?',['The charterparty readiness requirements, arrival status and any contractual conditions for tender','Only the vessel name','Only the freight rate','Whether the commodity price rose'],0,'Laytime consequences depend on a valid NOR under the actual charterparty wording.'),
    R => { const elapsed=r(R,72,144,12), excluded=r(R,6,30,6), allowed=r(R,48,96,12), rate=r(R,16,32,2)*1000; const excess=Math.max(0,elapsed-excluded-allowed); const cost=round(excess/24*rate); return numeric(`Statement of Facts shows ${elapsed} elapsed hours. ${excluded} hours are excluded and allowed laytime is ${allowed} hours. Demurrage is ${money(rate)}/day. Demurrage amount?`,cost,'$',`(${elapsed} − ${excluded} − ${allowed}) ÷ 24 × ${money(rate)} = ${money(cost)}.`); },
    R => choice('Under a typical time charter, which cost is normally for the charterer rather than the owner?',['Voyage bunkers used while the vessel is on hire','Crew wages','Hull insurance','Technical maintenance'],0,'Time charterers normally control commercial employment and pay voyage-related bunkers, while owners retain technical operation and crew.'),
    R => { const days=r(R,4,12), cons=r(R,20,45,5), fuel=r(R,450,750,50); const cost=days*cons*fuel; return numeric(`A vessel ballasts ${days} days, consuming ${cons} t/day of fuel at $${fuel}/t. Ballast bunker cost?`,cost,'$',`${days} × ${cons} × $${fuel} = ${money(cost)}.`); },
    R => { const laden=r(R,12,28,4), ballast=r(R,4,12,2), port=r(R,4,8); const total=laden+ballast+port; return numeric(`Route requires ${laden} laden days, ${ballast} ballast days and ${port} port days. Total voyage duration?`,total,'days',`${laden} + ${ballast} + ${port} = ${total} days.`); },
    R => choice('A charterer exposed to rising freight may use an FFA primarily to…',['Offset part of the freight-market exposure on a relevant route/index','Transfer title to the cargo','Replace the bill of lading','Guarantee vessel performance'],0,'Freight derivatives target market-rate exposure; they do not remove operational or basis risk between the actual voyage and the index.'),
    R => choice('In tanker freight, Worldscale 100 means…',['100% of the published Worldscale flat rate for that route','$100 per tonne','100 voyage days','A vessel speed of 100 knots'],0,'Worldscale points are percentage points of the route-specific published flat rate.'),
    R => { const flat=one(R,[18,22,26,30]), ws=r(R,70,160,10), qty=r(R,60,120,10)*1000; const rate=round(flat*ws/100,2), total=round(rate*qty); return numeric(`Worldscale flat rate is $${flat}/t and the fixture is WS${ws} on ${qty.toLocaleString('en-US')} t. Approximate freight?`,total,'$',`$${flat}/t × ${ws}% × ${qty.toLocaleString('en-US')} t = ${money(total)}.`); }
  );

  EXTRA.a4.push(
    R => { const face=r(R,4,20,2)*1000000, bps=r(R,40,160,20), days=r(R,30,120,30); const fee=round(face*(bps/10000)*(days/360)); return numeric(`Confirmed LC amount ${money(face)}, confirmation fee ${bps} bps p.a. for ${days} days on a 360-day basis. Approximate fee?`,fee,'$',`${money(face)} × ${bps}/10,000 × ${days}/360 = ${money(fee)}.`); },
    R => { const face=r(R,3,15,2)*1000000, disc=r(R,3,8), days=r(R,30,120,30); const cost=round(face*(disc/100)*(days/360)); return numeric(`A bank discounts a ${money(face)} deferred-payment LC at ${disc}% p.a. for ${days} days on a 360-day basis. Approximate discount cost?`,cost,'$',`${money(face)} × ${disc}% × ${days}/360 = ${money(cost)}.`); },
    R => { const qty=r(R,10,40,5)*1000, price=r(R,500,900,50), move=r(R,5,20,5); const add=qty*move; return numeric(`You sold ${qty.toLocaleString('en-US')} t open account. The mark-to-market moves $${move}/t in your favour before payment, increasing replacement exposure to the buyer. Additional exposure?`,add,'$',`${qty.toLocaleString('en-US')} × $${move} = ${money(add)}.`); },
    R => choice('Why are payment terms part of the commodity price?',['Because extra unsecured days consume funding and credit capacity','Because payment timing never affects return','Because banks set the commodity benchmark','Because Incoterms fix interest rates'],0,'A $/t margin is not comparable until you account for how long cash and credit are tied up.'),
    R => { const inv=r(R,20,60,10), rec=r(R,20,80,10), pay=r(R,10,50,10); const cycle=inv+rec-pay; return numeric(`Inventory days ${inv}, receivable days ${rec}, supplier payable days ${pay}. Approximate cash conversion cycle?`,cycle,'days',`${inv} + ${rec} − ${pay} = ${cycle} days.`); },
    R => choice('Why does a borrowing base apply advance rates or haircuts to collateral?',['To leave protection for price moves, costs and imperfect recoveries','To increase the trader’s leverage without limit','Because collateral value never changes','Only for tax reporting'],0,'The lender advances less than face value because collateral can fall in value or cost money to realise.'),
    R => { const eligible=r(R,8,24,2)*1000000, adv=one(R,[70,75,80,85]), drawn=r(R,2,10,2)*1000000; const max=eligible*adv/100; const avail=Math.max(0,max-drawn); return numeric(`Eligible collateral ${money(eligible)}, advance rate ${adv}%, existing borrowing ${money(drawn)}. Additional borrowing availability?`,avail,'$',`${money(eligible)} × ${adv}% − ${money(drawn)} = ${money(avail)}.`); },
    R => choice('Expected credit loss is useful commercially because…',['It converts probability and recovery assumptions into a cost that can be compared with margin','It predicts exactly when default occurs','It replaces credit limits','It removes legal risk'],0,'A simplified expected-loss charge helps compare two trades with different counterparty quality.'),
    R => choice('A high-margin deal that consumes nearly all remaining counterparty limit should be judged on…',['Margin relative to scarce limit and the downside if the buyer fails','Invoice size only','Whether the trader likes the buyer','Benchmark direction only'],0,'Credit limit is scarce balance-sheet capacity and should earn an adequate return.'),
    R => { const exp=r(R,2,12,2)*1000000, pd=one(R,[1,2,3,4,5]), lgd=one(R,[30,40,50,60]); const el=round(exp*(pd/100)*(lgd/100)); return numeric(`Exposure ${money(exp)}, one-year default probability ${pd}%, loss-given-default ${lgd}%. Simplified expected loss?`,el,'$',`${money(exp)} × ${pd}% × ${lgd}% = ${money(el)}.`); },
    R => { const gross=r(R,25,55,5), finance=r(R,4,12,2), el=r(R,1,8), capital=r(R,1,5); const net=gross-finance-el-capital; return numeric(`Gross margin $${gross}/t, finance $${finance}/t, expected credit cost $${el}/t and capital charge $${capital}/t. Credit-adjusted margin?`,net,'$/t',`${gross} − ${finance} − ${el} − ${capital} = $${net}/t.`); }
  );

  EXTRA.a5.push(
    R => choice('Why can gross position and net flat-price exposure tell different stories?',['Offsetting hedges can reduce flat-price sensitivity while gross operational and liquidity commitments remain large','They are always identical','Gross position is only for accountants','Net exposure measures vessel size'],0,'A desk can be flat to price and still have large settlement, basis, financing and execution obligations.'),
    R => { const phys=r(R,40,120,10)*1000, hedge=r(R,20,100,10)*1000, delta=one(R,[0.7,0.8,0.9,1.0]); const exp=round(phys-hedge*delta); return numeric(`Long physical ${phys.toLocaleString('en-US')} t. Short proxy hedge ${hedge.toLocaleString('en-US')} t with hedge delta ${delta}. Approximate residual equivalent exposure?`,exp,'t',`${phys.toLocaleString('en-US')} − ${hedge.toLocaleString('en-US')} × ${delta} = ${exp.toLocaleString('en-US')} t.`); },
    R => { const pos=r(R,20,80,10)*1000, shock=r(R,30,120,10); const loss=pos*shock; return numeric(`Stress scenario: a ${pos.toLocaleString('en-US')} t net-long position faces a $${shock}/t price fall. Flat-price stress loss?`,-loss,'$',`${pos.toLocaleString('en-US')} × $${shock} = ${money(loss)} loss.`); },
    R => { const price=r(R,2,8)*1000000, freight=r(R,1,4)*1000000, credit=r(R,1,6)*1000000; const total=price+freight+credit; return numeric(`Stress losses: price ${money(price)}, freight ${money(freight)}, counterparty ${money(credit)}. Combined scenario loss?`,-total,'$',`${money(price)} + ${money(freight)} + ${money(credit)} = ${money(total)} loss.`); },
    R => { const qty=r(R,20,80,10)*1000, basis=r(R,5,25,5); const pnl=qty*basis; return numeric(`A ${qty.toLocaleString('en-US')} t cross-hedged position suffers a $${basis}/t adverse basis move while flat price is hedged. Residual basis P&L?`,-pnl,'$',`${qty.toLocaleString('en-US')} × $${basis} = ${money(pnl)} loss.`); },
    R => { const physical=r(R,4,12)*1000000, hedge=r(R,3,11)*1000000; const net=physical-hedge; return numeric(`Physical leg gains ${money(physical)} while hedge loses ${money(hedge)}. Combined hedge result?`,net,'$',`${money(physical)} − ${money(hedge)} = ${money(net)}.`); },
    R => choice('Why can margin calls create a crisis on a profitable hedged trade?',['The paper leg settles cash now while the offsetting physical gain may arrive much later','A profitable hedge never needs cash','Margin is paid only after delivery','Banks automatically fund every call'],0,'Liquidity timing, not only final economics, determines whether a desk survives the path to settlement.'),
    R => { const cash=r(R,10,30,5)*1000000, calls=r(R,4,14,2)*1000000, supplier=r(R,2,10,2)*1000000, delay=r(R,1,6)*1000000; const head=cash-calls-supplier-delay; return numeric(`Available cash ${money(cash)}; margin calls ${money(calls)}, supplier payments ${money(supplier)}, customer delay reserve ${money(delay)}. Liquidity headroom?`,head,'$',`${money(cash)} − ${money(calls)} − ${money(supplier)} − ${money(delay)} = ${money(head)}.`); }
  );

  EXTRA.a6.push(
    R => choice('Why must hedge sizing start from contract units and lot sizes?',['Because exchange contracts are discrete and a nominal tonne exposure may not divide exactly into whole lots','Because lots determine Incoterms','Because lot size removes basis risk','Only brokers care about contract size'],0,'Execution requires translating physical exposure into actual exchange lots and accepting any rounding residual.'),
    R => choice('Variation margin belongs in hedge design because…',['A correct hedge can still create large interim cash calls','It changes the physical quality','It guarantees profit','It replaces collateral'],0,'Derivative settlement timing can be as important as terminal P&L for a physical merchant.'),
    R => { const qty=r(R,10,80,5)*1000, lot=one(R,[25,50,100]); const lots=Math.round(qty/lot); return numeric(`Exposure is ${qty.toLocaleString('en-US')} t and the hedge contract is ${lot} t per lot. Approximate whole lots required?`,lots,'lots',`${qty.toLocaleString('en-US')} ÷ ${lot} ≈ ${lots} lots.`); },
    R => choice('A cross-hedge should be monitored for…',['Basis and correlation instability between the exposure and proxy contract','Only exchange fees','Only physical title','No residual risk'],0,'A proxy can behave well in normal markets and diverge when the underlying physical market is stressed.'),
    R => { const qty=r(R,20,70,10)*1000, basis=r(R,4,18,2); const pnl=qty*basis; return numeric(`Your flat price is hedged on ${qty.toLocaleString('en-US')} t, but the physical basis weakens $${basis}/t. Basis P&L?`,-pnl,'$',`${qty.toLocaleString('en-US')} × $${basis} = ${money(pnl)} loss.`); },
    R => { const qty=r(R,20,70,10)*1000, phys=r(R,6,20,2), proxy=phys-r(R,-6,6,2); const residual=(phys-proxy)*qty; return numeric(`Physical value changes $${phys}/t and the proxy hedge offsets $${proxy}/t on ${qty.toLocaleString('en-US')} t. Residual move?`,residual,'$',`(${phys} − ${proxy}) × ${qty.toLocaleString('en-US')} = ${money(residual)}.`); },
    R => { const fixed=r(R,70,110,5), floating=fixed+r(R,-15,15,5), qty=r(R,20,80,10)*1000; const settle=(floating-fixed)*qty; return numeric(`You receive floating and pay fixed $${fixed}/t in a swap on ${qty.toLocaleString('en-US')} t. Floating settles at $${floating}/t. Swap settlement?`,settle,'$',`(${floating} − ${fixed}) × ${qty.toLocaleString('en-US')} = ${money(settle)}.`); },
    R => { const fixed=r(R,70,110,5), avg=fixed+r(R,-12,12,3), qty=r(R,20,80,10)*1000; const settle=(avg-fixed)*qty; return numeric(`Monthly-average swap: receive average, pay fixed $${fixed}/t on ${qty.toLocaleString('en-US')} t. Monthly average is $${avg}/t. Settlement?`,settle,'$',`(${avg} − ${fixed}) × ${qty.toLocaleString('en-US')} = ${money(settle)}.`); },
    R => { const qty=r(R,10,50,5)*1000, delta=one(R,[0.25,0.4,0.55,0.7]), lot=one(R,[25,50,100]); const lots=Math.round(qty*delta/lot); return numeric(`Options cover ${qty.toLocaleString('en-US')} t with delta ${delta}. Futures lot size is ${lot} t. Approximate delta-hedge lots?`,lots,'lots',`${qty.toLocaleString('en-US')} × ${delta} ÷ ${lot} ≈ ${lots} lots.`); },
    R => { const exposure=r(R,20,80,10)*1000, ratio=one(R,[0.7,0.8,0.9,1.0]); const hedge=round(exposure*ratio); return numeric(`Physical exposure is ${exposure.toLocaleString('en-US')} t and chosen hedge ratio is ${ratio}. Hedge tonnage?`,hedge,'t',`${exposure.toLocaleString('en-US')} × ${ratio} = ${hedge.toLocaleString('en-US')} t.`); },
    R => { const qty=r(R,20,70,10)*1000, spread=r(R,4,18,2); const pnl=qty*spread; return numeric(`Purchase and sale pricing windows leave ${qty.toLocaleString('en-US')} t exposed to a calendar spread. The spread moves $${spread}/t against the book. P&L?`,-pnl,'$',`${qty.toLocaleString('en-US')} × $${spread} = ${money(pnl)} loss.`); }
  );

  EXTRA.a7.push(
    R => choice('The all-in price of exchange-priced metal is best viewed as…',['Benchmark metal price plus the relevant physical premium/discount and contract adjustments','Only the exchange screen','Only warehouse rent','Only freight'],0,'Separating benchmark and physical differential is essential for pricing and hedging the two risks correctly.'),
    R => { const qty=r(R,500,3000,250), move=r(R,20,90,10); const pnl=qty*move; return numeric(`Regional premium strengthens $${move}/t on ${qty.toLocaleString('en-US')} t you are short to a customer. Premium P&L?`,-pnl,'$',`${qty.toLocaleString('en-US')} × $${move} = ${money(pnl)} loss.`); },
    R => choice('Can physical premium exposure always be assumed unhedgeable on exchange?',['No. Availability depends on metal and region; for example, dedicated aluminium premium contracts exist','Yes, all premiums are unhedgeable by definition','Every premium is hedged by base LME futures automatically','Premiums are not prices'],0,'Base-metal futures do not hedge a premium automatically, but dedicated premium products exist for some markets, so the exposure must be checked rather than assumed.'),
    R => { const qty=r(R,500,2500,250), rent=one(R,[0.35,0.45,0.55,0.7]), days=r(R,30,150,30), finance=r(R,10,35,5); const cost=round(qty*rent*days + qty*finance); return numeric(`Store ${qty.toLocaleString('en-US')} t for ${days} days at $${rent}/t/day plus $${finance}/t financing/carry. Total carry cost?`,cost,'$',`${qty.toLocaleString('en-US')} × $${rent} × ${days} + ${qty.toLocaleString('en-US')} × $${finance} = ${money(cost)}.`); },
    R => { const dmt=r(R,5,15)*1000, grade=one(R,[20,22,24,26,28]), payable=one(R,[95,96,97]); const metal=round(dmt*grade/100*payable/100,1); return numeric(`Concentrate is ${dmt.toLocaleString('en-US')} dmt at ${grade}% copper with ${payable}% payable metal. Approximate payable copper tonnes?`,metal,'t',`${dmt.toLocaleString('en-US')} × ${grade}% × ${payable}% = ${metal.toLocaleString('en-US')} t.`,.1); },
    R => { const qty=r(R,500,3000,250), lot=25; const lots=Math.round(qty/lot); return numeric(`Copper exposure is ${qty.toLocaleString('en-US')} t. Standard LME Copper lot size is ${lot} t. Approximate whole lots?`,lots,'lots',`${qty.toLocaleString('en-US')} ÷ ${lot} ≈ ${lots} lots.`); },
    R => { const qty=r(R,500,3000,250), spread=r(R,20,80,10); const pnl=qty*spread; return numeric(`Purchase and sale quotation periods leave ${qty.toLocaleString('en-US')} t exposed. The relevant LME calendar spread moves $${spread}/t against you. P&L?`,-pnl,'$',`${qty.toLocaleString('en-US')} × $${spread} = ${money(pnl)} loss.`); },
    R => { const buy=r(R,90,180,10), sell=buy+r(R,40,120,10), freight=r(R,15,45,5), finance=r(R,5,20,5); const m=sell-buy-freight-finance; return numeric(`Buy premium $${buy}/t, sell premium $${sell}/t, freight $${freight}/t, finance $${finance}/t. Net physical premium margin?`,m,'$/t',`${sell} − ${buy} − ${freight} − ${finance} = $${m}/t.`); },
    R => { const qty=r(R,500,2500,250), lmeMove=r(R,100,400,50), premMove=r(R,20,80,10); const residual=qty*premMove; return numeric(`A ${qty.toLocaleString('en-US')} t metal cargo is fully flat-price hedged against a $${lmeMove}/t LME move, but the regional premium weakens $${premMove}/t. Residual P&L?`,-residual,'$',`The LME move is hedged; ${qty.toLocaleString('en-US')} × $${premMove} = ${money(residual)} premium loss.`); },
    R => choice('Why should a metals trader distinguish on-warrant from off-warrant inventory?',['Deliverability, financing and availability to the exchange system differ','They are identical inventories','Off-warrant metal has no owner','Only tax treatment changes'],0,'Warehouse status affects how quickly metal can satisfy exchange or physical demand and therefore affects local tightness.')
  );

  EXTRA.a8.push(
    R => { const crude=r(R,65,90), gas=r(R,85,115), dist=r(R,90,120); const crack=round((2*gas+dist-3*crude)/3,1); return numeric(`Crude $${crude}/bbl, gasoline $${gas}/bbl, distillate $${dist}/bbl. Simple 3-2-1 crack per barrel of crude?`,crack,'$/bbl',`(2 × ${gas} + ${dist} − 3 × ${crude}) ÷ 3 = $${crack}/bbl.`,.1); },
    R => { const prompt=r(R,70,100), deferred=prompt+r(R,-8,8); const spread=prompt-deferred; return numeric(`Prompt crude is $${prompt}/bbl and deferred crude $${deferred}/bbl. Prompt minus deferred?`,spread,'$/bbl',`${prompt} − ${deferred} = $${spread}/bbl.`); },
    R => { const contango=r(R,2,8), storage=one(R,[0.6,0.8,1.0,1.2]), finance=one(R,[0.4,0.6,0.8,1.0]), loss=one(R,[0.1,0.2,0.3]); const net=round(contango-storage-finance-loss,1); return numeric(`Forward premium $${contango}/bbl; storage $${storage}, finance $${finance}, losses $${loss}/bbl. Net carry?`,net,'$/bbl',`${contango} − ${storage} − ${finance} − ${loss} = $${net}/bbl.`,.1); },
    R => choice('A cargo priced on one month and sold on another is economically a position in…',['The relevant calendar spread between the two pricing windows','Only flat Brent','Only freight','No market risk'],0,'Pricing-window mismatch is a calendar-spread exposure even if the physical volume is matched.'),
    R => { const qty=r(R,300,900,100)*1000, spread=r(R,1,5); const pnl=qty*spread; return numeric(`A ${qty.toLocaleString('en-US')} bbl cargo has purchase and sale pricing windows one month apart. The calendar spread moves $${spread}/bbl against you. P&L?`,-pnl,'$',`${qty.toLocaleString('en-US')} × $${spread} = ${money(pnl)} loss.`); },
    R => { const buyAvg=r(R,70,100), sellAvg=buyAvg+r(R,-4,6); const qty=r(R,300,900,100)*1000; const pnl=(sellAvg-buyAvg)*qty; return numeric(`Purchase QP averages $${buyAvg}/bbl and sale QP averages $${sellAvg}/bbl on ${qty.toLocaleString('en-US')} bbl. Pricing-window contribution?`,pnl,'$',`(${sellAvg} − ${buyAvg}) × ${qty.toLocaleString('en-US')} = ${money(pnl)}.`); },
    R => { const v1=r(R,20,60,10), s1=one(R,[0.1,0.2,0.3]), v2=r(R,20,60,10), s2=one(R,[0.8,1.0,1.2]); const sulfur=round((v1*s1+v2*s2)/(v1+v2),2); return numeric(`Blend ${v1} kbbl at ${s1}% sulfur with ${v2} kbbl at ${s2}% sulfur. Approximate blended sulfur?`,sulfur,'%',`(${v1} × ${s1} + ${v2} × ${s2}) ÷ (${v1} + ${v2}) = ${sulfur}%.`,.01); },
    R => { const high=r(R,90,120), low=r(R,70,95), vHigh=r(R,20,50,10), vLow=r(R,20,50,10), sale=r(R,86,108); const input=high*vHigh+low*vLow, revenue=sale*(vHigh+vLow), margin=round(revenue-input); return numeric(`Blend ${vHigh} kbbl costing $${high}/bbl and ${vLow} kbbl costing $${low}/bbl, then sell blend at $${sale}/bbl. Gross blend contribution before other costs, in $000?`,margin,'$000',`${sale} × ${vHigh+vLow} − (${high} × ${vHigh} + ${low} × ${vLow}) = ${margin} thousand dollars.`); },
    R => choice('A useful oil P&L attribution separates…',['Flat price, grade/location differential, timing spread, freight, blending/quality and execution','Only invoice revenue','Only benchmark price','Only demurrage'],0,'Breaking the result into drivers shows whether the desk earned merchant margin or accidentally took market risk.'),
    R => choice('For a delivered oil arbitrage, the destination benchmark is not enough because…',['Freight, losses, quality, timing and terminal costs determine the origin netback','Benchmarks include every logistics cost','Cargoes have no quality differences','Freight is fixed globally'],0,'The arbitrage survives only if the full delivered economics work.'),
    R => { const dest=r(R,90,125), freight=r(R,2,7), losses=one(R,[0.2,0.4,0.6]), terminal=one(R,[0.3,0.5,0.8]); const nb=round(dest-freight-losses-terminal,1); return numeric(`Destination value $${dest}/bbl, freight $${freight}, losses $${losses}, terminal costs $${terminal}/bbl. Origin netback?`,nb,'$/bbl',`${dest} − ${freight} − ${losses} − ${terminal} = $${nb}/bbl.`,.1); }
  );

  EXTRA.a9.push(
    R => { const brent=r(R,60,100), slope=one(R,[0.11,0.12,0.13,0.14]), constTerm=one(R,[0.2,0.5,0.8]); const price=round(brent*slope+constTerm,2); return numeric(`Oil-indexed LNG formula is ${slope} × Brent + $${constTerm}/MMBtu. Brent is $${brent}/bbl. Contract price?`,price,'$/MMBtu',`${slope} × ${brent} + ${constTerm} = $${price}/MMBtu.`,.01); },
    R => choice('A regasification slot has option value because…',['Terminal capacity can be scarce exactly when destination gas prices are strongest','It fixes the source gas price','It removes shipping risk','It guarantees demand'],0,'Infrastructure access is both a cost and a right to monetise a destination market.'),
    R => { const rate=r(R,80,180,20)*1000, days=r(R,20,40,5), energy=r(R,3,4)*1000000; const per=round(rate*days/energy,2); return numeric(`LNG vessel hire is ${money(rate)}/day for ${days} days. Cargo energy is ${energy.toLocaleString('en-US')} MMBtu. Hire cost per MMBtu before fuel?`,per,'$/MMBtu',`${money(rate)} × ${days} ÷ ${energy.toLocaleString('en-US')} = $${per}/MMBtu.`,.01); },
    R => { const asia=r(R,15,25), fa=r(R,2,5), europe=asia+r(R,-4,4), fe=r(R,1,4); const diff=round((asia-fa)-(europe-fe),1); return numeric(`Asia value $${asia}/MMBtu with $${fa} logistics. Europe value $${europe}/MMBtu with $${fe} logistics. Asia netback minus Europe netback?`,diff,'$/MMBtu',`(${asia} − ${fa}) − (${europe} − ${fe}) = $${diff}/MMBtu.`,.1); },
    R => choice('Gas storage is not only seasonal inventory; commercially it is also…',['An option to inject when cheap and withdraw when valuable, subject to capacity and rate constraints','A guaranteed arbitrage','A replacement for pipelines','A fixed-price contract'],0,'Injection and withdrawal rights create flexibility whose value changes with volatility and the forward curve.'),
    R => { const winter=r(R,12,22), summer=winter-r(R,2,8), inject=one(R,[0.3,0.5,0.7]), withdraw=one(R,[0.2,0.4,0.6]), finance=one(R,[0.2,0.4,0.6]); const net=round(winter-summer-inject-withdraw-finance,1); return numeric(`Winter gas $${winter}/MMBtu, summer $${summer}. Injection $${inject}, withdrawal $${withdraw}, finance $${finance}/MMBtu. Net seasonal carry?`,net,'$/MMBtu',`${winter} − ${summer} − ${inject} − ${withdraw} − ${finance} = $${net}/MMBtu.`,.1); },
    R => { const cap=r(R,2,6)*1000000, spread=r(R,1,5), usage=one(R,[50,60,70,80]); const value=round(cap*usage/100*spread); return numeric(`Storage working capacity ${cap.toLocaleString('en-US')} MMBtu, expected usable cycle ${usage}% and seasonal spread $${spread}/MMBtu before costs. Gross spread value?`,value,'$',`${cap.toLocaleString('en-US')} × ${usage}% × $${spread} = ${money(value)}.`); },
    R => { const dest=r(R,15,24), source=r(R,7,13), ship=r(R,2,5), regas=one(R,[0.4,0.7,1.0]), boil=one(R,[0.2,0.4,0.6]); const m=round(dest-source-ship-regas-boil,1); return numeric(`Destination $${dest}/MMBtu, source $${source}, shipping $${ship}, regas $${regas}, boil-off allowance $${boil}/MMBtu. Simplified LNG arbitrage margin?`,m,'$/MMBtu',`${dest} − ${source} − ${ship} − ${regas} − ${boil} = $${m}/MMBtu.`,.1); },
    R => { const energy=r(R,3,4)*1000000, loss=one(R,[0.5,0.8,1.0,1.2]), value=r(R,12,22); const cost=round(energy*loss/100*value); return numeric(`Cargo energy ${energy.toLocaleString('en-US')} MMBtu. Total voyage/handling loss is ${loss}% and replacement value is $${value}/MMBtu. Value of lost energy?`,cost,'$',`${energy.toLocaleString('en-US')} × ${loss}% × $${value} = ${money(cost)}.`); }
  );

  EXTRA.a10.push(
    R => { const peak=r(R,20,60,10), off=r(R,20,80,10), hp=r(R,4,8), ho=r(R,8,16,4); const mwh=peak*hp+off*ho; return numeric(`A shaped contract delivers ${peak} MW for ${hp} peak hours and ${off} MW for ${ho} off-peak hours. Total MWh?`,mwh,'MWh',`${peak} × ${hp} + ${off} × ${ho} = ${mwh} MWh.`); },
    R => { const load=r(R,80,140,10), hedge=r(R,70,130,10), hours=r(R,4,10); const residual=(load-hedge)*hours; return numeric(`Actual load averages ${load} MW for ${hours} hours while your baseload hedge is ${hedge} MW. Residual energy position?`,residual,'MWh',`(${load} − ${hedge}) × ${hours} = ${residual} MWh.`); },
    R => { const peakP=r(R,90,180,10), offP=r(R,30,90,10), peakM=r(R,20,60,10), offM=r(R,40,100,10); const avg=round((peakP*peakM+offP*offM)/(peakM+offM),1); return numeric(`Peak price €${peakP}/MWh on ${peakM} MWh; off-peak €${offP}/MWh on ${offM} MWh. Load-weighted average price?`,avg,'€/MWh',`(${peakP} × ${peakM} + ${offP} × ${offM}) ÷ (${peakM+offM}) = €${avg}/MWh.`,.1); },
    R => choice('A clean spark spread differs from a simple spark spread because it…',['Also deducts the carbon cost associated with generation emissions','Uses no gas price','Ignores plant efficiency','Is only for renewable plants'],0,'For thermal generation, carbon can materially change dispatch economics and the merit order.'),
    R => choice('What can hedge locational power basis more directly than a system-wide futures position?',['A locational spread/transmission instrument where such a market exists','More baseload volume at the same hub','A bill of lading','A bunker swap'],0,'System futures hedge flat price; congestion instruments target the price difference between locations.'),
    R => { const qty=r(R,20,100,20)*1000, spread=r(R,5,30,5); const pnl=qty*spread; return numeric(`You are long Zone A and short Zone B on ${qty.toLocaleString('en-US')} MWh. A-minus-B spread widens €${spread}/MWh in your favour. P&L?`,pnl,'€',`${qty.toLocaleString('en-US')} × €${spread} = €${pnl.toLocaleString('en-US')}.`); },
    R => { const flow=r(R,50,200,25), spread=r(R,5,30,5), hours=r(R,4,12,2); const rent=flow*spread*hours; return numeric(`A constrained interconnector carries ${flow} MW for ${hours} hours while the zonal price spread is €${spread}/MWh. Gross congestion value?`,rent,'€',`${flow} × ${hours} × €${spread} = €${rent.toLocaleString('en-US')}.`); },
    R => { const error=r(R,5,25), hours=r(R,2,8), price=r(R,100,350,25); const cost=error*hours*price; return numeric(`Renewable output is ${error} MW below forecast for ${hours} hours and replacement/imbalance energy costs €${price}/MWh. Gross shortfall cost?`,cost,'€',`${error} × ${hours} × €${price} = €${cost.toLocaleString('en-US')}.`); },
    R => { const power=r(R,80,160,10), gas=r(R,20,50,5), heat=one(R,[1.8,2.0,2.2]), carbon=one(R,[0.32,0.36,0.4]), eua=r(R,50,100,10), other=r(R,4,12,2); const margin=round(power-gas*heat-carbon*eua-other,1); return numeric(`Power €${power}/MWh, gas €${gas}/MWh(th), heat rate ${heat}, emissions ${carbon} tCO₂/MWh(e), EUA €${eua}/t and other variable cost €${other}/MWh. Clean spark margin?`,margin,'€/MWh',`${power} − ${gas} × ${heat} − ${carbon} × ${eua} − ${other} = €${margin}/MWh.`,.1); },
    R => { const margin=r(R,10,40,5), mw=r(R,50,200,25), hours=r(R,4,12,2); const value=margin*mw*hours; return numeric(`A flexible plant has positive dispatch margin €${margin}/MWh for ${mw} MW across ${hours} hours. Gross dispatch contribution?`,value,'€',`${margin} × ${mw} × ${hours} = €${value.toLocaleString('en-US')}.`); }
  );

  EXTRA.a11.push(
    R => { const begin=r(R,20,50,5), prod=r(R,80,140,10), imp=r(R,5,20,5), use=r(R,70,120,10), exp=r(R,10,30,5); const end=begin+prod+imp-use-exp; return numeric(`Beginning stocks ${begin} Mt, production ${prod}, imports ${imp}, domestic use ${use}, exports ${exp} Mt. Ending stocks?`,end,'Mt',`${begin} + ${prod} + ${imp} − ${use} − ${exp} = ${end} Mt.`); },
    R => { const stocks=r(R,18,45,3), use=r(R,90,180,15); const ratio=round(stocks/use*100,1); return numeric(`Ending stocks are ${stocks} Mt and annual use is ${use} Mt. Stocks-to-use ratio?`,ratio,'%',`${stocks} ÷ ${use} × 100 = ${ratio}%.`,.1); },
    R => choice('Why must storage economics include shrink and quality deterioration, not only rent?',['Stored grain can lose saleable quantity or value over time','Shrink is always zero','Futures reimburse quality losses','Storage rent includes all market risks'],0,'Carry is profitable only after every cost of keeping the physical commodity saleable.'),
    R => { const rent=r(R,3,9), finance=r(R,2,7), shrink=one(R,[0.5,1.0,1.5,2.0]); const req=round(rent+finance+shrink,1); return numeric(`Storage $${rent}/t, finance $${finance}/t and expected shrink/quality cost $${shrink}/t. Minimum deferred premium needed to break even?`,req,'$/t',`${rent} + ${finance} + ${shrink} = $${req}/t.`,.1); },
    R => choice('Why are independent certificates of quality/weight important in agricultural trade?',['They create agreed evidence for acceptance, pricing adjustments and claims','They guarantee futures prices','They replace the sale contract','They remove weather risk'],0,'The contract needs an agreed measurement process because quality and weight directly determine invoice value.'),
    R => { const qty=r(R,20,70,10)*1000, freight=r(R,20,50,5); const total=qty*freight; return numeric(`Ocean freight is $${freight}/t on ${qty.toLocaleString('en-US')} t of grain. Total freight?`,total,'$',`${qty.toLocaleString('en-US')} × $${freight} = ${money(total)}.`); },
    R => { const days=r(R,1,5), rate=r(R,15,30,3)*1000; const cost=days*rate; return numeric(`A grain vessel incurs ${days} days of demurrage at ${money(rate)}/day. Cost?`,cost,'$',`${days} × ${money(rate)} = ${money(cost)}.`); },
    R => { const dest=r(R,250,360,10), freight=r(R,25,55,5), inland=r(R,8,22,2), quality=r(R,0,12,2); const nb=dest-freight-inland-quality; return numeric(`Destination value $${dest}/t; ocean freight $${freight}, inland logistics $${inland}, expected quality discount $${quality}/t. Origin netback?`,nb,'$/t',`${dest} − ${freight} − ${inland} − ${quality} = $${nb}/t.`); },
    R => { const sell=r(R,280,380,10), buy=sell-r(R,25,60,5), freight=r(R,20,45,5), quality=r(R,0,10,2), finance=r(R,2,8,2); const m=sell-buy-freight-quality-finance; return numeric(`Sell $${sell}/t, buy $${buy}/t, freight $${freight}, quality allowance $${quality}, finance $${finance}/t. Net agri margin?`,m,'$/t',`${sell} − ${buy} − ${freight} − ${quality} − ${finance} = $${m}/t.`); }
  );

  EXTRA.a12.push(
    R => { const prepay=r(R,2,10)*1000000, discount=r(R,2,6), months=r(R,3,9); const benefit=round(prepay*discount/100), annual=round((benefit/prepay)*(12/months)*100,1); return numeric(`A supplier offers a ${discount}% discount on ${money(prepay)} of material if you prepay ${months} months early. Ignoring default risk, approximate annualised discount yield?`,annual,'%',`${discount}% × 12/${months} ≈ ${annual}% annualised before credit risk.`,.1); },
    R => choice('When moving from FOB to CIF in a negotiation, the commercial question is not only freight cost but also…',['Which party now controls carriage, insurance arrangements and associated execution exposure','Whether the benchmark changes name','Whether title always transfers at destination','Whether the cargo needs documents'],0,'Changing delivery terms reallocates tasks and risks as well as invoice components.'),
    R => { const fob=r(R,600,900,20), freight=r(R,20,60,5), insurance=one(R,[1,2,3,4]), cif=fob+freight+insurance; return numeric(`FOB value $${fob}/t, main freight $${freight}/t and insurance allowance $${insurance}/t. Simplified CIF equivalent?`,cif,'$/t',`${fob} + ${freight} + ${insurance} = $${cif}/t.`); },
    R => { const qty=r(R,20,70,10)*1000, freight=r(R,20,50,5), handling=r(R,3,10); const cost=qty*(freight+handling); return numeric(`A contract change makes you responsible for $${freight}/t main carriage and $${handling}/t extra handling on ${qty.toLocaleString('en-US')} t. Added cost?`,cost,'$',`${qty.toLocaleString('en-US')} × (${freight} + ${handling}) = ${money(cost)}.`); },
    R => choice('A buyer-controlled quantity or pricing clause should be treated as…',['An economic option whose exercise can move your sourcing, hedge or margin','Pure legal boilerplate','A guaranteed upside for the seller','Something operations can price after signing'],0,'Control over future price, timing or quantity has value and should be identified before the commercial price is fixed.'),
    R => { const qty=r(R,20,70,10)*1000, m1=r(R,650,900,10), better=r(R,10,40,5), m2=m1-better; const value=qty*better; return numeric(`Buyer may choose the lower of Month 1 at $${m1}/t or Month 2 at $${m2}/t on ${qty.toLocaleString('en-US')} t. In this realised scenario, value transferred to the buyer versus being forced to Month 1?`,value,'$',`${qty.toLocaleString('en-US')} × ($${m1} − $${m2}) = ${money(value)}.`); },
    R => { const base=r(R,40,100,10)*1000, option=10, repl=r(R,5,20); const extra=base*option/100; const cost=extra*repl; return numeric(`Offtake volume is ${base.toLocaleString('en-US')} t with +${option}% buyer option. Extra tonnes cost $${repl}/t above contract economics when exercised. Realised option cost?`,cost,'$',`${base.toLocaleString('en-US')} × ${option}% × $${repl} = ${money(cost)}.`); },
    R => { const qty=r(R,20,70,10)*1000, late=r(R,1,8), rate=one(R,[0.15,0.2,0.25,0.3]); const ld=round(qty*late*rate); return numeric(`Contract provides liquidated damages of $${rate}/t/day on ${qty.toLocaleString('en-US')} t. Delivery is ${late} days late. Damages?`,ld,'$',`${qty.toLocaleString('en-US')} × ${late} × $${rate} = ${money(ld)}.`); },
    R => { const claim=r(R,1,6)*1000000, cap=r(R,1,5)*1000000; const payable=Math.min(claim,cap); return numeric(`Verified contractual claim is ${money(claim)} but the applicable liability cap is ${money(cap)}. Amount within the cap?`,payable,'$',`min(${money(claim)}, ${money(cap)}) = ${money(payable)}.`); },
    R => { const annual=r(R,50,180,10)*1000, margin=r(R,6,18,2), yrs=r(R,3,7), risk=r(R,1,5); const gross=annual*margin*yrs, reserve=annual*risk*yrs, net=gross-reserve; return numeric(`Offtake ${annual.toLocaleString('en-US')} t/year for ${yrs} years at $${margin}/t gross contribution, with $${risk}/t risk reserve. Undiscounted risk-adjusted life contribution?`,net,'$',`${annual.toLocaleString('en-US')} × (${margin} − ${risk}) × ${yrs} = ${money(net)}.`); }
  );
  /* @CONTENT-OVERHAUL-V6_1-END */
