import fs from 'fs';
import vm from 'vm';
import path from 'path';
import { fileURLToPath } from 'url';
const here=path.dirname(fileURLToPath(import.meta.url)), root=path.resolve(here,'..');
const ctx={window:{},Date,Math,console}; vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(root,'competitive.js'),'utf8'),ctx);
const C=ctx.window.WOT_COMP; let ok=0,bad=0;
const t=(n,v)=>{ if(v){ok++;console.log('  ✓ '+n)}else{bad++;console.log('  ✗ '+n)} };
t('6 competitive divisions',C.divisions.length===6);
t('Bronze to Master',C.divisions[0].id==='bronze'&&C.divisions.at(-1).id==='master');
t('6 original houses',C.houses.length===6&&new Set(C.houses.map(x=>x.id)).size===6);
t('18 achievements',C.achievements.length===18&&new Set(C.achievements.map(x=>x.id)).size===18);
t('week key starts Monday',C.weekKey(new Date(2026,7,26))==='2026-08-24');
t('promotion can move one tier',C.seasonMove('bronze',250,null)==='silver');
t('relegation cannot go below bronze',C.seasonMove('bronze',0,25)==='bronze');
t('top 5 promotes with placement',C.seasonMove('gold',0,3)==='platinum');
t('bottom placement demotes',C.seasonMove('gold',999,24)==='silver');
const a=C.localOpponents('2026-08-24','bronze',120), b=C.localOpponents('2026-08-24','bronze',120);
t('local preview deterministic',JSON.stringify(a)===JSON.stringify(b));
t('local preview has 24 unique traders',a.length===24&&new Set(a.map(x=>x.alias)).size===24);
t('preview rows clearly marked',a.every(x=>x.preview===true));
console.log(`\nCompetitive: ${ok} passati, ${bad} falliti`); process.exitCode=bad?1:0;
